cms/djangoapps/contentstore/views/library.py
cms/static/coffee/spec/main.coffee
cms/static/js/factories/library.js
cms/static/js/index.js
cms/static/js/spec/views/pages/index_spec.js
cms/static/js/spec/views/pages/library_spec.js
cms/static/js/views/pages/library_container.js
cms/static/js/views/utils/create_course_utils.js
cms/static/js/views/utils/create_library_utils.js
cms/templates/index.html
cms/templates/js/mock/mock-library-page.underscore
cms/templates/library.html
common/lib/xmodule/xmodule/library_content_module.py

Content Libraries - Additional UI updates

---

lms/templates/index.html

JIRA task: [OC-1381](https://tasks.opencraft.com/browse/OC-1381)
Up and running here: http://52.58.8.41/

Change index page header text for St. Gallen

---

cms/envs/common.py
common/lib/xmodule/setup.py
common/lib/xmodule/xmodule/library_content_module.py
common/lib/xmodule/xmodule/tests/test_library_content.py
lms/djangoapps/course_blocks/api.py
lms/djangoapps/course_blocks/transformers/library_content.py
lms/djangoapps/course_blocks/transformers/tests/test_library_content.py
setup.py

This PR implements the first version of "Adaptive Content Block", a specialized version of "Randomized Content Block" that will select and display library content based on information from an external adaptive learning tool (Domoscio).
It doesn't add any custom functionality to the new block; it only makes sure that the new block supports the same functionality as the existing block, and that the new block can be added to a unit.
cf. [OC-2149](https://tasks.opencraft.com/browse/OC-2149)
**Screenshots**
"Advanced" menu in Studio (with both `"library_content"` and `"adaptive_library_content"` in advanced modules):
Adaptive Content Block added to a unit:
EDIT dialog for Adaptive Content Block:
Adaptive Content Block after selecting a library:
**Test instructions**
1. Follow instructions on …

First version of Adaptive Content Block

---

cms/envs/aws.py
cms/envs/yaml_config.py
lms/envs/aws.py
lms/envs/yaml_config.py

(cherry picked from commit 8c9aa7d3f3e1692ed48a73f3aa898d3d9c1aa340)

Allow configuring TLS for celery broker

---

cms/djangoapps/contentstore/tests/test_course_settings.py
cms/djangoapps/models/settings/course_metadata.py
cms/envs/common.py
common/djangoapps/adaptive_learning/admin.py
common/djangoapps/adaptive_learning/config/models.py
common/djangoapps/adaptive_learning/migrations/0001_initial.py
lms/templates/dashboard.html

This pull requests allows the ability for admins to enable adaptive learning across an entire instance. This pull requests also creates the situation where, by default, adaptive learning features are disabled, and must be enabled via the Django admin.
**JIRA tickets:** OC-3298
**Dependencies:** None
**Screenshots:** TBD
**Testing instructions:** TBD
1. Database change has occurred. Added a new model AdaptiveLearningEnabledFlag
**Reviewers**

Instance-wide option to enable adaptive learning

---

common/djangoapps/student/admin.py

This is a backport of https://github.com/edx/edx-platform/pull/16166.

Add search box to CourseEnrollmentAllowed admin interface.

---

common/test/acceptance/tests/lms/test_lms.py
lms/djangoapps/course_wiki/tests/tests.py
lms/djangoapps/course_wiki/views.py

CAM-67 Change default article name to be course name instead of slug

---

lms/djangoapps/courseware/tests/test_course_info.py
lms/djangoapps/courseware/views/views.py
lms/templates/courseware/info.html

Backports https://github.com/edx/edx-platform/pull/16671 to Ginkgo.
Re: CAM-4 @pomegranited

Customize course info title

---

lms/djangoapps/ccx/tests/test_views.py
lms/djangoapps/ccx/urls.py
lms/djangoapps/ccx/utils.py
lms/djangoapps/ccx/views.py
lms/templates/ccx/coach_dashboard.html
lms/templates/ccx/enrollment.html

This PR simplifies and improves the Enrollment tab of CCX dashboard by:
1. Marking the missing phrases for the translation.
1. Merging two sections: Student list management and Batch enrollment into one as they have very similar functionality.
It is a backport of https://github.com/edx/edx-platform/pull/17160 to `ginkgo.1-campus`.
LMS: TBD
Studio: TBD
(before you start, see _Author notes and concerns_)
1. Make sure you have CCX enabled (see [here](http://edx.readthedocs.io/projects/open-edx-ca/en/latest/set_up_course/custom_courses.html) for the details)
2. Go to CCX Dashboard and click _Enrollment_ tab.
3. Pick some number of users who have been already registered in the platform. Type some of them by …

Simplify layout of the Enrollment tab of CCX dashboard

---

cms/__init__.py
lms/__init__.py
lms/monkey_patch/__init__.py
lms/monkey_patch/django.py

JIRA Ticket: OC-4097
Applying patch to migrations for Campus, according to: #121

Fix for migrations running slow on Django 1.8

---

requirements/edx/openstack.txt

Uses latest release of `django-storage-swift`, cf https://github.com/open-craft/edx-platform/pull/119
**Reviewer**

Uses newly tagged django-storage-swift==1.2.19

---

cms/djangoapps/contentstore/views/import_export.py

We noticed that very large exports were sometimes failing due to timeouts. This PR makes two changes:
1. The default fallback export system now uses ``StreamingHttpResponse`` so the entire export file doesn't need to be loaded into memory. 
2. The export URL generated now only uses the fallback ``export_output_handler``  if the artefact file storage is explicitly set to ``FileSystemStorage``
**JIRA tickets**: OC-4282 
* Using SWIFT Storage:
* LMS: https://ginkgo-export-fix.sandbox.opencraft.hosting/
* Studio: https://studio-ginkgo-export-fix.sandbox.opencraft.hosting/
* Using ``FileSystemStorage``:
1. Create a large course over 500MB in size. 
2. Export the course. 
3. The course download should start immediately despite the large size.
* When …

Fix course export issues

---

openedx/core/djangoapps/course_groups/serializers.py
openedx/core/djangoapps/course_groups/tests/test_api_views.py
openedx/core/djangoapps/course_groups/views.py

This is a dummy PR for reviewing the changes made for the 'list users in a cohort' endpoint before pulling into @viadanna's branch for the rest of related code.

BB-82 Implement an endpoint to get the users in a cohort

---

common/djangoapps/student/admin.py

This cherry-picks https://github.com/edx/edx-platform/pull/19106
See testing instructions and discussions there.

Fix error when saving CourseEnrollment in admin

---

openedx/core/djangoapps/oauth_dispatch/jwt.py

Cherry-picked from [this upstream commit](https://github.com/edx/edx-platform/commit/da1c2a119ba675fcf239dee2b55d2fefc2b50b0f).

Fix Elevation in permission over OAuth

---

common/djangoapps/track/backends/mongodb.py
common/lib/xmodule/xmodule/mongo_utils.py

Upstream PR: https://github.com/edx/edx-platform/pull/20819

[BB-1289] Add support for MongoDB authentication databases.

---

lms/templates/support/certificates.html

This has already been patched in the upstream master branch

[BB-1416] Fix XSS vulnerability in the Certificates Support page

---

common/djangoapps/student/forms.py
common/test/acceptance/tests/lms/test_account_settings.py
lms/djangoapps/verify_student/tests/test_views.py
lms/djangoapps/verify_student/views.py
openedx/core/djangoapps/user_api/accounts/__init__.py
openedx/core/djangoapps/user_api/accounts/serializers.py
openedx/core/djangoapps/user_api/accounts/tests/test_views.py
openedx/core/djangoapps/user_authn/views/tests/test_register.py

(cherry picked from commit [df14f5cdf6c303b5ad6b38d72391aed0dea124bf](https://github.com/edx/edx-platform/commit/df14f5cdf6c303b5ad6b38d72391aed0dea124bf))

[BB-1132] Decrease `NAME_MIN_LENGTH` to 1

---

cms/envs/production.py
lms/envs/production.py

See https://github.com/edx/edx-platform/pull/21567

SE-1541 backport broker heartbeat configuration to ironwood

---

lms/djangoapps/mobile_api/users/tests.py
lms/djangoapps/mobile_api/users/views.py

This backports https://github.com/edx/edx-platform/pull/21610 to our ironwood branch.

SE-1071 port user_logged_in signal sending to ironwood

---

openedx/core/djangoapps/schedules/resolvers.py
openedx/core/djangoapps/schedules/tests/test_resolvers.py

This backport the recently released security patch from master.
**Reviewer:**

BB-2105: Backport security patch

---

common/lib/capa/capa/capa_problem.py
common/lib/capa/capa/tests/test_capa_problem.py

Patch ironwood capa problem
(cherry picked from commit b4dd41841fbfc312aade9d89cc50b98a6a8e444c)

SE-2161 Merge pull request #23102 from edx/patch-ironwood-capa-problem

---

common/djangoapps/enrollment/serializers.py
common/djangoapps/enrollment/tests/fixtures/course-enrollments-api-list-valid-data.json
common/djangoapps/enrollment/tests/test_views.py
common/djangoapps/enrollment/urls.py
common/djangoapps/enrollment/views.py
lms/djangoapps/courseware/access_utils.py
lms/djangoapps/support/tests/test_views.py
lms/envs/test.py
openedx/core/djangoapps/content/block_structure/store.py

This PR adds the customizations from YTP Ginkgo branch to opencraft-release/ironwood.2
**JIRA tickets**: BB-1389
**Testing instructions**: TBD

[BB-1389] Update enrollment serializer to add finished courses and grades.

---

cms/static/js/certificates/views/certificate_editor.js
cms/static/js/certificates/views/certificate_preview.js
cms/static/js/certificates/views/signatory_details.js
cms/static/js/certificates/views/signatory_editor.js
cms/static/js/maintenance/force_publish_course.js
cms/static/js/models/settings/course_details.js
cms/static/js/models/settings/course_grading_policy.js
cms/static/js/views/abstract_editor.js
cms/static/js/views/asset.js
cms/static/js/views/course_info_handout.js
openedx/core/djangoapps/cors_csrf/templates/cors_csrf/xdomain_proxy.html
openedx/features/learner_profile/static/learner_profile/js/views/badge_view.js
openedx/features/learner_profile/static/learner_profile/js/views/section_two_tab.js
openedx/features/learner_profile/static/learner_profile/js/views/share_modal_view.js
themes/red-theme/lms/templates/ace_common/edx_ace/common/base_body.html
themes/stanford-style/lms/templates/courseware/course_about_sidebar_header.html

Cherry picked from commit edd9b02d520f7bf4dadc110ab46455556325dc93
Using the [test instance](https://manage.opencraft.com/instance/20000/edx-appserver/13111/), run OpenCraft's [manual instance checklist](https://gitlab.com/opencraft/documentation/private/blob/jill/clarify-checklist/checklists/manual_instance_test.md#how-to-elevate-a-user) to ensure basic functionality is unaffected by this change.
**Author Notes & Concerns**
1. Since this change was already merged upstream, we don't have to check each individual change here.
**Reviewer**

SE-2866 Merge pull request #180 from edx/sustaining-xsslint-security-fixes

---

lms/templates/student_account/register.underscore
lms/templates/verify_student/test/fake_softwaresecure_response.html
openedx/features/learner_profile/static/learner_profile/templates/badge_list.underscore
openedx/features/learner_profile/static/learner_profile/templates/badge_placeholder.underscore

PROD-1532
PROD-1533
PROD-1577
PROD-1578
(cherry-picked from commit 46becdc5777783f51307ce43c52e89112533e569)

Fixes xss issues.

---

lms/templates/student_account/register.underscore
lms/templates/verify_student/test/fake_softwaresecure_response.html
openedx/features/learner_profile/static/learner_profile/templates/badge_list.underscore
openedx/features/learner_profile/static/learner_profile/templates/badge_placeholder.underscore

This PR applies a patch to ``opencraft-release/ironwood.2-asu-ytp`` branch
**JIRA ticket**: [SE-3007](https://tasks.opencraft.com/browse/SE-3007)
**Reviewers**

Apply XSS security fix 

---

lms/templates/student_account/register.underscore
lms/templates/verify_student/test/fake_softwaresecure_response.html
openedx/features/learner_profile/static/learner_profile/templates/badge_list.underscore
openedx/features/learner_profile/static/learner_profile/templates/badge_placeholder.underscore

This PR applies a patch to ``opencraft-release/ironwood.2-asu-ytp-prod`` branch
**JIRA ticket**: [SE-3007](https://tasks.opencraft.com/browse/SE-3007)
**Reviewers**

Apply XSS security fix to ironwood.2-asu-ytp-prod

---

cms/static/js/views/components/add_xblock.js
cms/static/js/views/components/add_xblock_button.js
cms/static/js/views/course_rerun.js
cms/static/js/views/instructor_info.js
cms/static/js/views/list_item_editor.js
cms/static/js/views/metadata.js
cms/static/js/views/video/translations_editor.js
cms/static/js/views/xblock_validation.js

PR to apply XSS patch to our juniper branch.

Apply security XSS patch to juniper branch

---

cms/static/js/views/components/add_xblock.js
cms/static/js/views/components/add_xblock_button.js
cms/static/js/views/course_rerun.js
cms/static/js/views/instructor_info.js
cms/static/js/views/list_item_editor.js
cms/static/js/views/metadata.js
cms/static/js/views/video/translations_editor.js
cms/static/js/views/xblock_validation.js

PR to apply the XSS patch to our ironwood branch.

Apply security XSS patch to ironwood branch

---

cms/static/js/views/container.js
cms/static/js/views/experiment_group_edit.js
cms/static/js/views/learning_info.js
cms/static/js/views/list_item.js
lms/templates/ccx/coach_dashboard.html
lms/templates/components/card/card.underscore
lms/templates/edxnotes/note-item.underscore
lms/templates/edxnotes/tab-item.underscore
lms/templates/fields/field_image.underscore
lms/templates/instructor/instructor_dashboard_2/enrollment-code-lookup-links.underscore
lms/templates/learner_dashboard/program_card.underscore
lms/templates/video.html

This PR contains cherry-picked commits from https://github.com/edx/edx-platform/pull/24937

[SE-3234] - Apply upstream XSS patches

---

openedx/core/djangoapps/content/block_structure/signals.py

Fixes block structure not caching when cache invalidation is enabled by catching `BlockStructureNotFound` exception raised when clearing course from cache.
Even if the block structure wasn't found when clearing the course from cache to invalidate it, it shouldn't be raised, because that would interrupt the updating of the block structure in cache.
**JIRA tickets**: SE-3439, [OSPR-5116](https://openedx.atlassian.net/browse/OSPR-5116)
**Upstream PR**: https://github.com/edx/edx-platform/pull/25543
1. Setup Block Structure Caching using S3 Buckets, to do that follow these steps:
1. Add the configuration in the bottom of this comment to LMS and Studio
1. Make sure that the S3 IAM User has permissions to access that bucket
1. Add the following two Waffle switches to …

[SE-3439] Fixes block structure not caching when cache invalidation is enabled

---

cms/envs/common.py
cms/urls.py
lms/djangoapps/gdpr_user_retirement/tests/test_views.py
lms/djangoapps/gdpr_user_retirement/urls.py
lms/djangoapps/gdpr_user_retirement/views.py
lms/envs/common.py
lms/urls.py

This PR adds a new django app to allow the GDPR user retirement via Open edX's REST API. Prior to this the only way to trigger the user retirement was either by the user themself clicking "Delete my account" in the account setting page or via creating a User Retirement request by admin. With these changes, the user retirement process can be triggered using REST API. 
**Jira Tickets:** [SE-3405](https://tasks.opencraft.com/browse/SE-3405)
**Sandbox Url:**
LMS: https://se-3405-test.opencraft.hosting/
Studio: https://studio.se-3405-test.opencraft.hosting/
1. Create one or more user accounts that you want to retire. 
2. Go to the django admin -> Django Oauth Toolkit -> Application and copy the client ID and client secret for the `retirement-service-backend-service`. …

[SE-3405] Django app to allow user retirement via API

---

common/djangoapps/enrollment/serializers.py
lms/djangoapps/support/static/support/js/views/certificates.js
lms/static/js/certificates/views/certificate_whitelist.js
lms/static/js/courseware/certificates_api.js
lms/static/js/discovery/views/course_card.js
lms/static/js/discovery/views/facet.js
lms/static/js/edxnotes/views/note_group.js
lms/static/js/edxnotes/views/note_item.js
lms/static/js/edxnotes/views/tabs/course_structure.js
lms/static/js/edxnotes/views/tabs/recent_activity.js
lms/static/js/groups/views/course_cohort_settings_notification.js
lms/static/js/student_account/views/account_section_view.js
lms/static/js/verify_student/views/error_view.js

This is a merge of https://github.com/open-craft/edx-platform/pull/301 in ASU branch.

[BB-3349] IM security fixes

---

cms/templates/js/add-xblock-component-button.underscore
cms/templates/js/add-xblock-component.underscore
cms/templates/js/asset-upload-modal.underscore
cms/templates/js/course_grade_policy.underscore
cms/templates/js/due-date-editor.underscore
cms/templates/js/metadata-dict-entry.underscore
cms/templates/js/metadata-file-uploader-entry.underscore
cms/templates/js/metadata-list-entry.underscore
cms/templates/js/metadata-number-entry.underscore
cms/templates/js/metadata-option-entry.underscore
cms/templates/js/validation-error-modal.underscore
cms/templates/js/verification-access-editor.underscore
cms/templates/js/video/metadata-translations-entry.underscore
cms/templates/js/video/metadata-translations-item.underscore
cms/templates/js/video/transcripts/messages/transcripts-choose.underscore
cms/templates/js/video/transcripts/messages/transcripts-found.underscore
cms/templates/js/video/transcripts/metadata-videolist-entry.underscore
cms/templates/js/xblock-string-field-editor.underscore
common/lib/capa/capa/templates/imageinput.html
common/lib/symmath/symmath/formula.py
common/lib/symmath/symmath/symmath_check.py
common/lib/xmodule/xmodule/block_metadata_utils.py
common/static/js/capa/drag_and_drop/base_image.js
common/test/test_sites/test_site/templates/static_templates/contact.html
lms/djangoapps/teams/static/teams/templates/team-member.underscore
lms/static/js/instructor_dashboard/student_admin.js

**Sandbox**:
-    LMS: https://fal-984-xss-fixes.opencraft.hosting/
-    Studio: https://studio.fal-984-xss-fixes.opencraft.hosting/
- verify that the changes match the patches (these all applied cleanly):
- https://discuss.openedx.org/t/security-im-patch-for-xss-fixes-7/4198
- https://discuss.openedx.org/t/security-im-patch-for-xss-fixes-8/4231
- https://discuss.openedx.org/t/security-im-patch-for-xss-fixes-9/4297
- verify that the notes xss fix is not required for this branch: https://github.com/edx/edx-platform/commit/f1324710af5559375e0e13cb0d58f3b820c9ae27 | https://discuss.openedx.org/t/security-patch-for-xss-fixes-on-learner-notes-feature/4241
- verify that an instance with this branch provisions successfully (check the …

FAL-984 port recent xss patches to common juniper branch

---

cms/djangoapps/contentstore/views/preview.py

This is a backport for https://github.com/open-craft/edx-platform/pull/323

 [BB-3710][Backport] Stop rendering Visibility button on libraries

---

requirements/edx/base.in
requirements/edx/base.txt
requirements/edx/development.txt
requirements/edx/github.in
requirements/edx/testing.txt

This PR backports the py2neo fix that is breaking Juniper deployments

fix: Backport py2neo fix workaround (edx#27186)

---

cms/static/js/models/settings/course_grader.js
cms/static/js/views/active_video_upload.js
common/djangoapps/third_party_auth/templates/third_party_auth/post_custom_auth_entry.html
common/lib/xmodule/xmodule/js/src/collapsible.js
common/lib/xmodule/xmodule/js/src/video/09_poster.js
lms/static/js/api_admin/views/catalog_preview.js
lms/static/js/discovery/views/filter_bar.js

Two patches applied:
* https://discuss.openedx.org/t/security-im-patch-for-xss-fixes-10/4702
* https://github.com/edx/edx-platform/commit/a0fdc97f1704659d26e167de3fbf2ab8c371d67b
**JIRA tickets**:
- [BB-4083](https://tasks.opencraft.com/browse/BB-4083)
Use manual test checklist.

[BB-4083] Backport security patches

---

lms/envs/common.py
lms/templates/courseware/course_about.html

backport of https://github.com/edx/edx-platform/pull/27197

BB-3954 Add toggle for enrollment behavior

---

lms/djangoapps/certificates/views/webview.py
lms/envs/common.py

This is a backport PR of https://github.com/edx/edx-platform/pull/25777

Cherry Pick of BB-3306 (Juniper)

---

docs/swagger.yaml
lms/djangoapps/instructor/apps.py
lms/djangoapps/instructor/tests/test_api.py
lms/djangoapps/instructor/urls.py
lms/djangoapps/instructor/views/api.py
lms/djangoapps/instructor/views/api_urls.py
openedx/core/lib/api/serializers.py

feat: Add REST endpoints for problem response report generation that can be driven by MFEs. (#27313)
(cherry picked from commit 161e3560dde9edf1c2bacedf2dd442dc077a8cbf)

feat: Add REST endpoints for problem response report generation that can be driven by MFEs. (#27313)

---

requirements/edx/base.txt

This PR fixes deployment failure issue happening today.
https://tasks.opencraft.com/browse/BB-4669
ASAP

[BB-4669] Change lti-consumer-xblock==2.4

---

cms/celery.py
lms/celery.py

Cf. [SE-4734](https://tasks.opencraft.com/browse/SE-4734)
Cherry-picks upstream security fix for course imports into common branch for Koa.
**Test instructions**
*(Omitted for security reasons.)*
**Reviewers**

fix: update lxml parser for celery tasks to be more secure

---

lms/static/js/spec/dateutil_factory_spec.js
package-lock.json
package.json

This is backport fix of https://github.com/edx/edx-platform/pull/28486

[BB-4649] Backport: Fix duplicate Arabic month in course start date

---

common/lib/xmodule/xmodule/css/capa/display.scss

This cherry-picks the changes from https://github.com/edx/edx-platform/pull/28562 into our koa branch.

[FAL-2358] Fix RTL issue with capa problems.

---

lms/djangoapps/courseware/tabs.py

Revert "Remove priority from static main tabs to make tab sorting function works correctly"
This reverts commit 762cccdd4b59cae8831630f0a9fea1c0f0a2ded1.

Revert SE-4305

---

lms/djangoapps/courseware/tabs.py

Revert "Remove priority from static main tabs to make tab sorting function works correctly"
This reverts commit 762cccdd4b59cae8831630f0a9fea1c0f0a2ded1.

Revert SE-4305 for ESME

---

openedx/core/djangoapps/user_api/accounts/permissions.py
openedx/core/djangoapps/user_api/accounts/tests/test_views.py
openedx/core/djangoapps/user_api/accounts/views.py
openedx/core/djangoapps/user_authn/views/logout.py
openedx/core/djangoapps/user_authn/views/tests/test_logout.py

This PR applies the security patches required backported to Koa. Cherry-picked from https://github.com/overhangio/edx-platform/commit/78da3d86b79e808462b88f219efb90bf8253a5d1
and https://github.com/overhangio/edx-platform/commit/b63c01fb38a60f4581bdecbc528fa64cc3d3ef0d
**Jira Tickets:** [SE-5163](https://tasks.opencraft.com/browse/SE-5163)
- Verify that all the required changes from the two commits above are included.
**Reviewers:**

[SE-5163] Apply security patches for xss and email search from logout page

---

openedx/core/djangoapps/user_api/accounts/permissions.py
openedx/core/djangoapps/user_api/accounts/tests/test_views.py
openedx/core/djangoapps/user_api/accounts/views.py
openedx/core/djangoapps/user_authn/views/logout.py
openedx/core/djangoapps/user_authn/views/tests/test_logout.py

This PR cherry-picks two commits containing security fixes.

BB-5394 Security fixes

---

openedx/core/djangoapps/user_api/accounts/permissions.py
openedx/core/djangoapps/user_api/accounts/tests/test_views.py
openedx/core/djangoapps/user_api/accounts/views.py
openedx/core/djangoapps/user_authn/views/logout.py
openedx/core/djangoapps/user_authn/views/tests/test_logout.py

This PR includes two security fixes released by edX.

[BB-5394] Security fixes

---

common/djangoapps/third_party_auth/tests/test_views.py
common/djangoapps/third_party_auth/views.py

This backports https://github.com/openedx/edx-platform/pull/30220 to Lilac.

chore: backport security patch [BB-6111]

---

lms/templates/logout.html

This cherry-picks the security fix https://github.com/openedx/edx-platform/pull/30542 into the shared Lilac branch.

fix: cross-site scripting vulnerability on logout page [BB-6342]

---

lms/templates/logout.html

fix: cross-site scripting vulnerability on logout page - esme [BB-6342]

---

lms/templates/logout.html

Backport of https://github.com/open-craft/edx-platform/pull/473.

fix: cross-site scripting vulnerability on logout page - uq [BB-6342]

---

lms/templates/logout.html

Backport of https://github.com/open-craft/edx-platform/pull/473.

fix: cross-site scripting vulnerability on logout page - asu-ytp [BB-6342]

---

package-lock.json
package.json

Cherry-picked from the `open-release/maple.master` branch.

cherry-pick: Upgrade npm package @edx/studio-frontend to ^1.19.1 to fix missingng assets

---

common/djangoapps/student/models.py
common/djangoapps/student/tests/test_events.py
common/djangoapps/student/tests/test_models.py
common/lib/xmodule/xmodule/course_metadata_utils.py
common/lib/xmodule/xmodule/course_module.py
common/lib/xmodule/xmodule/tests/test_course_metadata_utils.py
common/lib/xmodule/xmodule/tests/test_course_module.py
lms/djangoapps/courseware/access.py
lms/djangoapps/courseware/tests/test_access.py
lms/envs/common.py
openedx/core/djangoapps/content/course_overviews/models.py
openedx/core/djangoapps/content/course_overviews/tests/test_course_overviews.py

This is a backport of https://github.com/openedx/edx-platform/pull/29538 (and a cherry-pick of https://github.com/open-craft/edx-platform/pull/488) to the common Maple branch.
Merging as a clean cherry-pick.

feat[maple]: disable allowed enrollment if enrollment closed [BB-5195]

---

common/djangoapps/student/models.py
common/djangoapps/student/tests/test_events.py
common/djangoapps/student/tests/test_models.py
common/lib/xmodule/xmodule/course_metadata_utils.py
common/lib/xmodule/xmodule/course_module.py
common/lib/xmodule/xmodule/tests/test_course_metadata_utils.py
common/lib/xmodule/xmodule/tests/test_course_module.py
lms/djangoapps/courseware/access.py
lms/djangoapps/courseware/tests/test_access.py
lms/envs/common.py
openedx/core/djangoapps/content/course_overviews/models.py
openedx/core/djangoapps/content/course_overviews/tests/test_course_overviews.py

This is a backport of https://github.com/openedx/edx-platform/pull/29538 to the common Nutmeg branch.
Merging as an almost clean cherry-pick (it only had conflicts in `lms/envs/common.py`).

feat[nutmeg]: disable allowed enrollment if enrollment closed [BB-5195]

---

lms/djangoapps/instructor/tests/test_api.py
lms/djangoapps/instructor/tests/test_tools.py
lms/djangoapps/instructor/views/tools.py

This cherry-picks https://github.com/openedx/edx-platform/pull/30999 to the common Maple branch.
Merging as a clean cherry-pick.

fix[maple]: regenerate the cache on due date extensions [BB-6658]

---

openedx/core/djangoapps/user_authn/utils.py
openedx/core/djangoapps/user_authn/views/tests/test_logout.py

This backports https://github.com/openedx/edx-platform/pull/31256 to Maple.

fix[maple]: add fix for XSS Vulnerability and Open Redirect

---

openedx/core/djangoapps/user_authn/utils.py
openedx/core/djangoapps/user_authn/views/tests/test_logout.py

This backports https://github.com/openedx/edx-platform/pull/31256 to Nutmeg.

fix(nutmeg): add fix for XSS Vulnerability and Open Redirect

---

lms/djangoapps/support/tests/test_views.py
lms/djangoapps/support/views/manage_user.py

Backports the changes in https://github.com/openedx/edx-platform/pull/31393 to the nutmeg branch.

fix: Fix retiring user auth models on disable event (Nutmeg backport)

---

lms/djangoapps/support/tests/test_views.py
lms/djangoapps/support/views/manage_user.py

Backports the changes in https://github.com/openedx/edx-platform/pull/31393 to Maple.

fix: Fix retiring user auth models on disable event (maple backport)

---

cms/djangoapps/contentstore/tests/test_course_settings.py
cms/djangoapps/contentstore/views/course.py
cms/envs/common.py
cms/templates/widgets/header.html

See https://github.com/openedx/edx-platform/pull/32015.

feat: feature flag to disable Advanced Settings [BACKPORT]

---

cms/static/js/spec/views/pages/course_outline_spec.js
cms/static/js/views/modals/course_outline_modals.js
cms/templates/js/self-paced-due-date-editor.underscore

This backports https://github.com/openedx/edx-platform/pull/32094 to the common Nutmeg branch.

fix(nutmeg): remove relative due date limit

---

cms/djangoapps/contentstore/tests/test_course_settings.py
cms/djangoapps/contentstore/views/course.py
cms/templates/settings.html
cms/templates/settings_graders.html
cms/templates/widgets/header.html
common/djangoapps/student/auth.py

Backport of https://github.com/openedx/edx-platform/pull/32097.

fix: missing advance_settings_access template variable

---

cms/envs/common.py
lms/envs/common.py
openedx/core/djangoapps/user_authn/views/logout.py
openedx/core/djangoapps/user_authn/views/tests/test_logout.py

(cherry picked from commit 2a5f33a5f06b96ada78efe5c4dca4af210b9d260)
Upstream PR : https://github.com/openedx/edx-platform/pull/32193
OpenCraft ticket : [BB-7398](https://tasks.opencraft.com/browse/BB-7398)

feat: tpa automatic logout

---

cms/djangoapps/contentstore/views/course.py
cms/envs/common.py
cms/static/js/factories/settings_graders.js
cms/static/js/views/settings/grading.js
cms/static/sass/views/_settings.scss
cms/templates/settings_graders.html

(cherry picked from commit 7a7af8cdc16416ec8e3289f9482e734b58145b0e)
cherry pick for [PR#32406](https://github.com/openedx/edx-platform/pull/32406)

feat: default grade designations configurable from settings

---

common/djangoapps/student/roles.py

Backport of https://github.com/openedx/edx-platform/pull/32569.

fix: give superusers all studio permissions [BB-7481]

---

lms/djangoapps/courseware/tests/test_discussion_xblock.py
xmodule/discussion_block.py

Reverts open-craft/edx-platform#569
Based on this [conversation](https://github.com/open-craft/edx-platform/pull/573#issuecomment-1677291337).

Revert "Sync opencraft-release/palm.1 with Upstream 20230807-1691366566"

---

lms/templates/instructor/instructor_dashboard_2/membership.html

This backports https://github.com/openedx/edx-platform/pull/32998 to Nutmeg.

feat(nutmeg): allow disabling default beta tester enrollment notifications [BB-7751]

---

lms/templates/instructor/instructor_dashboard_2/membership.html

This backports https://github.com/openedx/edx-platform/pull/32998 to Palm.

feat(palm): allow disabling default beta tester enrollment notifications [BB-7751]
