common/lib/capa/capa/customrender.py
common/lib/capa/capa/templates/clarification.html
common/lib/xmodule/xmodule/css/capa/display.scss
common/static/js/spec/tooltip_manager_spec.js
common/static/js/src/tooltip_manager.js
common/test/acceptance/pages/lms/problem.py
common/test/acceptance/tests/lms/test_lms_matlab_problem.py
common/test/acceptance/tests/lms/test_lms_problems.py

This PR implements the ability to add an inline marker in the text of problems, which can reveal more information to the user when he hovers over it.
Below you can see a two clarification markers - the one on the left is active because the user is hovering over it. There is an un-hovered state seen on the right.
The tooltips can also contain HTML:
The following XML is taken from the bok choy test:
```xml
<problem markdown="null">
<p>
Given the data in Table 7 <clarification>Table 7: "Example PV Installation Costs",
Page 171 of Roberts textbook</clarification>, compute the ROI
<clarification>Return on Investment <strong>(per year)</strong></clarification> over 20 years.
</p>
<numericalresponse answer="6.5">
<textline label="Enter the annual ROI" trailing_text="%" />
</numericalresponse> …
```

Support for inline explanatory popups in problem XML

---

common/djangoapps/student/views.py
openedx/core/djangoapps/user_api/tests/test_views.py

JIRA task: [OC-1381](https://tasks.opencraft.com/browse/OC-1381)
Removing the honor code checkbox causes the registration form to fail, as the registration form assumes that agreeing to the honor code means agreeing to the terms of service as well. This pull request changes the registration view to make agreeing to the terms of service required only if the checkbox is displayed.
Upstream PR: https://github.com/edx/edx-platform/pull/11644

Don't require terms of service if checkbox is hidden

---

common/test/acceptance/tests/discussion/test_discussion.py
conf/locale/ar/LC_MESSAGES/django.po
conf/locale/es_419/LC_MESSAGES/django.po
conf/locale/fr/LC_MESSAGES/django.po
conf/locale/he/LC_MESSAGES/django.po
conf/locale/hi/LC_MESSAGES/django.po
conf/locale/ko_KR/LC_MESSAGES/django.po
conf/locale/pt_BR/LC_MESSAGES/django.po
conf/locale/ru/LC_MESSAGES/django.po
conf/locale/zh_CN/LC_MESSAGES/django.po
lms/djangoapps/courseware/tests/test_self_paced_overrides.py
lms/djangoapps/discussion_api/api.py
lms/djangoapps/discussion_api/tests/test_api.py
lms/djangoapps/django_comment_client/forum/tests.py
lms/djangoapps/django_comment_client/tests/test_utils.py
lms/djangoapps/django_comment_client/utils.py
openedx/core/djangoapps/content/course_structures/tests.py

This change renames all code instances of `discussion_module` and to `discussion_xblock`, and updates the file paths used in the locale config to reflect new file locations.
The only remaining references to `discussion_module` or `discussion-module` are JS or CSS-related, and unnecessary coffee/JS changes are prohibited by [OC-1623](https://tasks.opencraft.com/browse/OC-1623).
**JIRA tickets**: Final part of [OC-1623](https://tasks.opencraft.com/browse/OC-1623).
**Reviewers**

Renames discussion_module to discussion_xblock

---

lms/templates/navigation.html

Adds a link to OpenCraft.Hosting to the main navigation bar.
This PR is to demo deploying an update to a production instance, using OpenCraft.Hosting.

Add link to OpenCraft.Hosting to navigation [Demo]

---

common/djangoapps/adaptive_domoscio/views.py
lms/envs/common.py
lms/static/js/revisions/collections/revision_collection.js
lms/static/js/revisions/dashboard_revision_factory.js
lms/static/js/revisions/models/revision.js
lms/static/js/revisions/views/revision_list_view.js
lms/static/sass/multicourse/_dashboard.scss
lms/templates/dashboard.html
lms/templates/revisions/dashboard_revision_error.underscore
lms/templates/revisions/dashboard_revision_item.underscore
lms/templates/revisions/dashboard_revision_list.underscore
lms/templates/revisions/dashboard_revision_loading.underscore
lms/urls.py

This change implements an async display of pending revisions (see the [Adaptive Learning](https://tasks.opencraft.com/browse/OC-2127) epic). The display isn't hooked up to the Domoscio API yet, so the list of xblocks to display is currently [hard coded](#diff-55b798ee23a7fde8d1103408afcd0f16R736) in the view.
**JIRA tickets**: [OC-2153](https://tasks.opencraft.com/browse/OC-2153)
1. Setup a [fun-box](https://github.com/openfun/fun-boxes) against this branch (open-craft:bdero/revision-list).
1. Create a course in studio with two or three problem xblocks (multiple choice, drop down, etc).
1. Navigate to the course in the LMS using a staff user, and obtain the serialized XBlock locations using the `Staff Debug Info` modal: …

Implemented revision list on dashboard

---

common/lib/xmodule/xmodule/course_module.py
common/lib/xmodule/xmodule/library_content_module.py
common/lib/xmodule/xmodule/tests/test_library_content.py
common/lib/xmodule/xmodule/tests/test_util_adaptive_learning.py
common/lib/xmodule/xmodule/util/adaptive_learning.py
lms/djangoapps/course_blocks/transformers/tests/test_library_content.py

This PR extends the new Adaptive Content Block in two ways:
* It adds logic for notifying Domoscio that the parent unit of an ACB has been accessed by a learner.
* It changes the way child blocks are selected for display: Instead of selecting `max_count` children randomly, ACBs now query Domoscio for information about pending reviews to determine which children to show (if any).
The PR also adds a new course-wide setting called "Adaptive Learning Configuration" which can be used to specify necessary information for communicating with the Domoscio API.
cf. [OC-2150](https://tasks.opencraft.com/browse/OC-2150), [OC-2151](https://tasks.opencraft.com/browse/OC-2151)
**Implementation**
When sending a "Unit viewed" event, ACB assumes that the corresponding unit exists in Domoscio's database (in …

Adaptive Content Block: Send "Unit viewed" event, selectively display review questions

---

common/djangoapps/track/backends/adaptive_learning.py
common/djangoapps/track/backends/tests/test_adaptive_learning.py
common/lib/xmodule/xmodule/library_content_module.py
common/lib/xmodule/xmodule/tests/test_library_content.py
common/lib/xmodule/xmodule/tests/test_util_adaptive_learning.py
common/lib/xmodule/xmodule/util/adaptive_learning.py
lms/djangoapps/course_blocks/transformers/tests/test_library_content.py
lms/envs/common.py
setup.py

This PR adds logic for notifying Domoscio when a learner submits a review question.
cf. [OC-2152](https://tasks.opencraft.com/browse/OC-2152)
**Implementation**
When a learner submits a review question, ACB needs to send an `EventResult` event for the "knowledge node student" object that links the learner to the review question to Domoscio. The event must include information about the result that the learner obtained (pass/fail).
To make this possible, this PR introduces a new `TRACKING_BACKEND` called `AdaptiveLearningBackend`. Like other existing backends, the `AdaptiveLearningBackend` listens to events that the platform generates when users interact with courses. When it receives a [`problem_check` event](https://edx.readthedocs.io/projects/devdata/en/latest/internal_data_formats/tracki …

Adaptive Content Block: Send results to external service when learner submits review question

---

common/djangoapps/adaptive_learning/tests/base.py
common/djangoapps/adaptive_learning/tests/test_utils.py
common/djangoapps/adaptive_learning/tests/test_views.py
common/djangoapps/adaptive_learning/utils.py
common/djangoapps/adaptive_learning/views.py
common/djangoapps/track/backends/adaptive_learning.py
common/lib/xmodule/xmodule/library_content_module.py
common/lib/xmodule/xmodule/tests/test_library_content.py
common/lib/xmodule/xmodule/tests/test_util_adaptive_learning.py
common/lib/xmodule/xmodule/util/adaptive_learning.py
lms/envs/common.py
lms/static/js/revisions/collections/revision_collection.js
lms/static/js/revisions/views/revision_list_view.js
lms/templates/dashboard.html
lms/urls.py

This PR follows up on #47, which added basic functionality for displaying a list of pending revisions on a learner's dashboard. It adds logic for displaying actual revisions (instead of a list of links to hard-coded blocks).
This PR also updates the URL for fetching pending reviews to point to the new API that Domoscio introduced a few days ago.
cf. [OC-2154](https://tasks.opencraft.com/browse/OC-2154)
**Screenshots**
**Basic setup**
1. Follow instructions on the [epic](https://tasks.opencraft.com/browse/OC-2127) to set up a FUN box.
2. Switch to this branch (`display-revisions`) and install the new block via
```sh
pip install -r requirements/edx/local.txt
```
3. Create a new content library and add a few problems to it.
4. Create a new course and add `"adaptive_library_content"` to …

Learner dashboard: Populate list of pending reviews with data from adaptive learning service

---

common/lib/xmodule/xmodule/tests/test_util_adaptive_learning.py
common/lib/xmodule/xmodule/util/adaptive_learning.py

This PR extends the logic for obtaining pending reviews to handle the case where the external adaptive learning service does not know about a given student. This can happen if the student:
* is not enrolled in the course that the system is fetching pending reviews for.
* has never interacted with adaptive learning content in the course (i.e., student is enrolled in current course but has never visited a unit containing an Adaptive Content Block before).
Follows up on #51.
**Basic setup**
1. Follow instructions on the [epic](https://tasks.opencraft.com/browse/OC-2127) to set up a FUN box.
2. Switch to this branch (`fix-display-revisions`) and install the new block via
```sh
pip install -r requirements/edx/local.txt
```
3. Create a new course.
4. To be able to work with the Domoscio API, …

Learner dashboard: Handle unknown student when displaying pending reviews

---

lms/templates/revisions/dashboard_revision_item.underscore

The Domoscio API will only return a pending review for a given unit and user if the date that its `"next_review_at"` property specifies is in the past.
As a result, users will never see a date on a pending revision that is in the future. But up until this commit, the UI would display the due date as "before DD/MM/YYYY". This is confusing because it suggests to a user that they are constantly missing deadlines for pending revisions.
To eliminate (or at least reduce) the potential for confusion, we now interpret the due date of a pending revision as "the date that this revision became due" (instead of "the date that this revision needs to be completed by"), and display "since DD/MM/YYYY" on the dashboard.
This approach was agreed upon at our status meeting with FUN and Domoscio.
Belongs to …

Learner dashboard: Make sure users don't get confused by due dates that are in the past

---

common/lib/xmodule/xmodule/tests/test_util_adaptive_learning.py
common/lib/xmodule/xmodule/util/adaptive_learning.py

Specify event type as `"type"` instead of `"event_type"` when sending an event notification to Domoscio.
This is necessary to trigger appropriate computations when sending a result event (upon submitting answer to review question).
The changes are supposed to fix an issue where Domoscio would keep sending back a pending review for a given unit after submitting an answer to a review question.
Part of the scope of [OC-2229](https://tasks.opencraft.com/browse/OC-2229).
**Test instructions**
The commands for running relevant tests are:
```sh
paver test_lib -l common/lib/xmodule/xmodule/tests/test_util_adaptive_learning.py
```
**Notes**
The changes introduced here are based on suggestions from Domoscio staff. I applied them to the Dogwood sandbox, but haven't been able to confirm that they …

Adaptive Content Block: Adjust payload that gets sent when notifying Domoscio about an event

---

common/lib/xmodule/xmodule/library_content_module.py
common/lib/xmodule/xmodule/tests/test_library_content.py
lms/static/sass/multicourse/_dashboard.scss
lms/templates/revisions/dashboard_revision_list.underscore

This PR introduces a couple of small adjustments to the code that implements adaptive learning functionality:
* The learner dashboard no longer displays any information about pending revisions if there are no pending reviews for the current user: Only a small subset of students registered with FUN will be taking the upcoming course that makes use of adaptive learning features. To avoid getting (a potentially large amount of) questions from users that are *not* taking the upcoming course, FUN decided that they do not want to show "You have no pending revisions." information on the dashboard.
* The logic for computing the list of questions to show for a given Adaptive Content Block has been modified to no longer check whether the block ID of the unit represented by the …

Adaptive Learning: Adjustments to learner dashboard and filtering logic for pending reviews

---

cms/djangoapps/contentstore/features/problem-editor.py
cms/djangoapps/contentstore/views/item.py
cms/djangoapps/models/settings/course_metadata.py
cms/static/js/spec/views/pages/course_outline_spec.js
cms/static/js/views/modals/course_outline_modals.js
cms/templates/course_outline.html
cms/templates/js/show-correctness-editor.underscore
common/lib/xmodule/xmodule/capa_base.py
common/lib/xmodule/xmodule/capa_base_constants.py
common/lib/xmodule/xmodule/capa_module.py
common/lib/xmodule/xmodule/modulestore/inheritance.py
common/lib/xmodule/xmodule/tests/test_capa_module.py

Adds `show_correctness` as a modulestore inherited setting.  This is editable from the sequence (subsection) XBlock.
**JIRA tickets**: [OC-2487](https://tasks.opencraft.com/browse/OC-2487)
**Discussions**: [Technical discovery document](https://docs.google.com/document/d/1yGAbIl5lZUXB_BTFDp5dx75fEypQHA7Ipg7M9PATKaw/edit)
**Sandbox URLs**:
* Studio: https://studio-pr14737.sandbox.opencraft.hosting/
* LMS: https://pr14737.sandbox.opencraft.hosting/
[MIT CAPA test course](https://pr14737.sandbox.opencraft.hosting/courses/course-v1:OpenCraft+CAPA1+2017/info) created with 
[show_correctness.course.tar.gz](https://github.com/open-craft/edx-platform/files/881752/show_correctness.course.tar.gz)
**Partner information**: 3rd party-hosted open edX instance …

Adds "Correctness Visibility" settings to subsection.

---

common/lib/xmodule/xmodule/capa_base.py
common/lib/xmodule/xmodule/tests/test_capa_module.py

Returns `success="submitted"` if correctness is withheld, and adds python tests.
**JIRA tickets**: [OC-2503](https://tasks.opencraft.com/browse/OC-2503)
**Discussions**: [Technical discovery document](https://docs.google.com/document/d/1yGAbIl5lZUXB_BTFDp5dx75fEypQHA7Ipg7M9PATKaw/edit)
* LMS: https://pr14737.sandbox.opencraft.hosting/
* Studio: https://studio-pr14737.sandbox.opencraft.hosting/
[MIT CAPA test course](https://pr14737.sandbox.opencraft.hosting/courses/course-v1:OpenCraft+CAPA1+2017/info) created with 
[show_correctness.course.tar.gz](https://github.com/open-craft/edx-platform/files/881752/show_correctness.course.tar.gz)
**Partner information**: 3rd party-hosted open edX instance
**Deployment targets**: edx.org and …

Ensure correctness isn't leaked by AJAX response

---

common/djangoapps/student/views.py
lms/djangoapps/courseware/tests/test_microsites.py
lms/templates/courses_list.html

The setting controls the number of courses displayed on the homepage.
Cherry-picks https://github.com/edx/edx-platform/pull/15476.
**Reviewers**:

Ability to set HOMEPAGE_COURSE_MAX via SiteConfiguration.

---

lms/djangoapps/bulk_enroll/serializers.py
lms/djangoapps/bulk_enroll/tests/test_views.py
lms/djangoapps/bulk_enroll/urls.py
lms/djangoapps/bulk_enroll/views.py
lms/envs/common.py
lms/envs/test.py
lms/urls.py
openedx/core/lib/api/permissions.py

Part of: https://tasks.opencraft.com/browse/OC-2453
Cherry-picked from PRs:
* https://github.com/edx/edx-platform/pull/15006
* ~~https://github.com/edx/edx-platform/pull/15584~~
* https://github.com/edx/edx-platform/pull/15579

Backport the upstreamed Bulk Enroll API

---

lms/djangoapps/discussion/views.py

The view that renders single discussion threads when linked to directly did not set a key in the template context that sets the default 'Add Post' topic area. This PR fixes that by imitating the correct view's method of assignment.
**JIRA tickets**: [OC-2984](https://tasks.opencraft.com/browse/OC-2984)
1. Navigate to a forum post
2. Copy link and paste in a new browser tab
3. Without patch, server should 500 with NameError. With patch, should display the forum post.
**Reviewers**

set discussion_default_topic_id in lms discussion single_thread view to prevent 500s when linked directly

---

common/static/common/templates/discussion/thread-show.underscore

This changes the text of the visibility warning to 'This post is visible to %(group_name)s.', removing "only".
To test, ensure that on the Instructor Dashboard, Cohorts are enabled for the course.
Also on the Instructor Dashboard, under Discussion settings, discussion topics must be divided by cohort.
Once these options are set, create a test discussion topic, view the topic, and see that the warning states "This post is visible to Cohort", instead of "This post is visible to only Cohort"

Change the visibility warning in discussions

---

common/lib/xmodule/xmodule/library_content_module.py
common/lib/xmodule/xmodule/tests/test_library_content.py
common/lib/xmodule/xmodule/util/adaptive_learning.py

This pull requests adds a user friendly message to adaptive content blocks that do not have any reviews returned. Instead of the current functionality which displays nothing, this displays a message that says 'No questions are currently scheduled for review. Please check back later.'
**JIRA tickets**: Implements OC-3297
**Merge deadline**: "None" 
1. Open an LMS instance
2. Navigate to a course / subsection that contains an Adaptive Content Block where no problems will show.
3. Ensure that the user friendly message is displayed.
1. None
**Reviewers**

Improve "empty state" for Adaptive Content Blocks

---

lms/static/js/ie11_find_array.js
lms/templates/main.html

Fixes a bug that makes discussion posts unable to be viewed by IE11 browsers. The bug uses invalid JavaScript  when cohorts are used in the discussion.
**JIRA tickets**: OC-3339
**Merge deadline**:  ASAP
1. Setup a Cloudera templated site.
2. Setup a course that has [cohorts](http://edx.readthedocs.io/projects/edx-partner-course-staff/en/latest/course_features/cohorts/cohort_config.html#enabling-cohorts-in-your-course).
3. Setup [divided discussions.](http://edx.readthedocs.io/projects/edx-partner-course-staff/en/latest/manage_discussions/set_up_divided_discussions.html#setting-up-divided-discussions)
4. On IE11 open up the created site on LMS.
5. Go to the course with cohorts and divided discussions.
6. View the …

OC-3339: Cloudera Barclays students unable to view discussion posts

---

cms/djangoapps/contentstore/tests/test_course_settings.py
cms/djangoapps/models/settings/course_metadata.py
common/djangoapps/adaptive_learning/admin.py
common/djangoapps/adaptive_learning/config/forms.py
common/djangoapps/adaptive_learning/config/models.py
common/djangoapps/adaptive_learning/config/tests/test_models.py
common/djangoapps/adaptive_learning/config/tests/utils.py
common/djangoapps/adaptive_learning/migrations/0002_courseadaptivelearningflag.py
lms/templates/dashboard.html

This PR adds course-level option to enable/disable Adaptive Learning feature through Django Admin panel. Adaptive Learning can be enabled by setting a global and an individual (per-course) flag.
**JIRA tickets**: Implements OC-3299.
**Dependencies:** None
**Author notes and concerns:** Database change has occurred. Added a new model `CourseAdaptiveLearningFlag`.
1. Run tests.
2. Go to Django Admin panel and play with values of adaptive learning flags. After changing the values, go to Course Advanced Settings in Studio (e.g. [localhost:18010/settings/advanced/course-v1:edX+DemoX+Demo_Course]()) and see whether Adaptive Learning section is present. It should be present only if both global and individual (per-course) flags are set to True.
**Reviewers**: …

Add course-level option to enable/disable Adaptive Learning feature.

---

cms/envs/common.py
common/lib/xmodule/xmodule/tests/test_video.py
common/lib/xmodule/xmodule/video_module/transcripts_utils.py
common/lib/xmodule/xmodule/video_module/video_handlers.py
common/lib/xmodule/xmodule/video_module/video_module.py
lms/djangoapps/courseware/tests/test_video_mongo.py
lms/djangoapps/mobile_api/video_outlines/serializers.py
lms/djangoapps/mobile_api/video_outlines/tests.py
lms/envs/common.py

Cherry-picks changes from https://github.com/edx/edx-platform/pull/16590 into Cloudera's release branch.
Also includes https://github.com/edx/edx-platform/pull/15475, because it fixes a bug with mobile videos that don't have transcripts, and removes merge conflicts with the `all_sources` change above.
25680f1 fixes tests broken because of differences between `master` and `ginkgo.1`.
**Settings**
```yaml
edx_ansible_source_repo: https://github.com/open-craft/configuration
configuration_version: opencraft-release/ginkgo.1-cloudera
openedx_release: open-release/ginkgo.1
EDXAPP_FEATURES:
ENABLE_MOBILE_REST_API: true
```

Adds "all_sources" to Mobile API and Course Blocks API video data

---

requirements/edx/github.txt

cf https://github.com/open-craft/django-wiki/pull/1
**JIRA tickets**: OC-3435
**Dependencies**: https://github.com/open-craft/django-wiki/pull/1
1. Deploy appserver for Pearson using this branch.
1. Note that the django-wiki package installs without error.
1. Before merging this, merge https://github.com/open-craft/django-wiki/pull/1, and change the `django-wiki` requirement to be:
```
git+https://github.com/open-craft/django-wiki.git@opencraft-release/ginkgo.1#egg=django-wiki==0.0.10
```
**Reviewers**

Updates django-wiki to fix Django requirement issue

---

requirements/edx/github.txt

cf https://github.com/open-craft/django-wiki/pull/1
**JIRA tickets**: OC-3435
**Dependencies**: https://github.com/open-craft/django-wiki/pull/1
1. Deploy appserver using this branch.
1. Note that the django-wiki package installs without error.
1. Before merging this, merge https://github.com/open-craft/django-wiki/pull/1, and change the `django-wiki` requirement to be:
```
git+https://github.com/open-craft/django-wiki.git@opencraft-release/ginkgo.1#egg=django-wiki==0.0.10
```
**Reviewers**
Signed-off-by: Tomasz Gargas <tomasz@opencraft.com>

Updates django-wiki to fix Django requirement issue.

---

common/lib/chem/setup.py

Because nltk==2.0.6 [has disappeared](https://pypi.python.org/pypi/nltk/2.0.6) (compare [2.0.5](https://pypi.python.org/pypi/nltk/2.0.5)), we use edX's fork.
**JIRA tickets**: None.
**Discussions**: None
**Partner information**: None
**Deployment targets**: Ocim prod.
**Merge deadline**: ASAP after provision is finished and after approval.
1. Wait for correct provision
2. Check log
3. Test instance
4. Merge
See in https://tasks.opencraft.com/browse/OC-3446
**Reviewers**
**Settings**
```yaml
```

Install chem nltk from edX fork.

---

common/lib/chem/setup.py

Two changes:
- Because nltk==2.0.6 [has disappeared](https://pypi.python.org/pypi/nltk/2.0.6) (compare [2.0.5](https://pypi.python.org/pypi/nltk/2.0.5)), we use edX's fork for "chem"
- Because django-wiki didn't mention an upper Django version, 2.0 was used and crashed, so we prefer to keep it <2.0
**JIRA tickets**: None.
**Discussions**: See https://github.com/open-craft/edx-platform/pull/79
**Partner information**: None
**Deployment targets**: Ocim prod.
**Merge deadline**: ASAP after provision is finished and after approval.
Same as https://github.com/open-craft/edx-platform/pull/79
None
**Reviewers**
**Settings**
```yaml
```

Install chem nltk from edX fork, and fix django-wiki dependency. Pearson.

---

common/lib/chem/setup.py
requirements/edx/github.txt

Two changes:
- Because nltk==2.0.6 [has disappeared](https://pypi.python.org/pypi/nltk/2.0.6) (compare [2.0.5](https://pypi.python.org/pypi/nltk/2.0.5)), we use edX's fork for "chem"
- Because django-wiki didn't mention an upper Django version, 2.0 was used and crashed, so we prefer to keep it <2.0
**JIRA tickets**: None.
**Discussions**: See https://github.com/open-craft/edx-platform/pull/79
**Partner information**: None
**Deployment targets**: Ocim prod.
**Merge deadline**: ASAP after provision is finished and after approval.
Same as https://github.com/open-craft/edx-platform/pull/79
None
**Reviewers**
**Settings**
```yaml
```

Install chem nltk from edX fork, and fix django-wiki dependency. Cloudera.

---

common/lib/chem/setup.py
requirements/edx/github.txt

Two changes:
- Because nltk==2.0.6 [has disappeared](https://pypi.python.org/pypi/nltk/2.0.6) (compare [2.0.5](https://pypi.python.org/pypi/nltk/2.0.5)), we use edX's fork for "chem"
- Because django-wiki didn't mention an upper Django version, 2.0 was used and crashed, so we prefer to keep it <2.0
**JIRA tickets**: None.
**Discussions**: See https://github.com/open-craft/edx-platform/pull/79
**Partner information**: None
**Deployment targets**: Ocim prod.
**Merge deadline**: ASAP after provision is finished and after approval.
Same as https://github.com/open-craft/edx-platform/pull/79
None
**Reviewers**
**Settings**
```yaml
```

Install chem nltk from edX fork, and fix django-wiki dependency. Campus.

---

lms/templates/courseware/course_about.html

Now that the new template inheritance was merged (https://github.com/edx/edx-platform/pull/16856) we can redefine specific blocks.
This adds some block names to existing code so that themes can redefine this blocks easily (without having to redefine the rest of the page).
This handles just course_about.html
**JIRA tickets**: None
**Discussions**: None
**Screenshots**: None
**Sandbox URL**: None
1. Without this change (i.e. with your normal devstack server), go to http://localhost:18000/courses/course-v1:edX+DemoX+Demo_Course/about and save the HTML in a file
2. Start a server which includes this change: https://github.com/edx/edx-platform/pull/16856, cherry-pick the commit as needed.
3. Apply the patch in this PR, …

Add some blocks to course_about.html

---

common/djangoapps/edxmako/paths.py
common/test/test-theme/lms/templates/courseware/courses.html
common/test/test-theme/lms/templates/courseware/info.html
common/test/test-theme/lms/templates/courseware/test-theme-custom.html
common/test/test-theme/lms/templates/dashboard.html
openedx/core/djangoapps/theming/tests/test_theme_style_overrides.py

This allows an overriding template from a theme to inherit from the
same corresponding standard template.
This is useful when you only want to override one or more named blocks,
but otherwise make no modifications to the standard template.
(cherry picked from [commit f6f29ca](https://github.com/open-craft/edx-platform/commit/f6f29ca49e98845cbc9afcc5c70c8670ad9f69fe), from https://github.com/edx/edx-platform/pull/16856/)

Allow theme template block overrides.

---

cms/envs/aws.py
lms/envs/aws.py

This pull request adds the AWS_LOCATION setting for used by ``django-storages`` to set a prefix for uploading files. It defaults to ``FILE_UPLOAD_STORAGE_PREFIX``.
1. Deploy instance with ``AWS_LOCATION`` set.
2. Uploads should go the the prefix specified in ``AWS_LOCATION``.
**Reviewers**

Add AWS_LOCATION setting for django-storages

---

cms/envs/common.py
lms/djangoapps/student_account/test/test_views.py
lms/djangoapps/student_account/views.py
lms/envs/common.py
lms/templates/emails/password_reset_subject.txt
lms/templates/registration/password_reset_email.html

This change allows Open edX operators to enable password reset
failure email notifications. This is mainly useful for
explicitly informing users that there's no account associated
with their email, so that users can be sure that there wasn't
a problem with the email system.
OSPR-1832
(cherry picked from commit c7c3ef694c7d2c5b24369d8cb2de35766cdfe3fd)

Add optional password reset failure emails

---

lms/templates/registration/password_reset_email.html

When backporting the invalid user handling, I missed a change from
site_name to platform_name in the upstream template, causing a blank
spot in the first sentence of the email.

Correct password reset email template

---

conf/locale/en/LC_MESSAGES/django.po
conf/locale/he/LC_MESSAGES/django.po
lms/templates/ccx/enrollment.html
lms/templates/courseware/course_about.html
lms/templates/enroll_staff.html
lms/templates/instructor/instructor_dashboard_2/membership.html

This PR adds a context to `enroll` string in Hebrew using `pgettext`.
In Hebrew there are different words for enroll depending on the context. Enroll as in enroll yourself is different as in enroll someone else.

(CAM-13) Add context to enroll

---

requirements/edx/openstack.txt

https://github.com/open-craft/django-storage-swift/pull/1 merged, so this reverts the change that uses that PR's branch.
**Sandbox URLs**
* LMS: https://pr112.sandbox.stage.opencraft.hosting/
* Studio: https://studio-pr112.sandbox.stage.opencraft.hosting/
Provisioning now with 193261e and persistent storage.
**Reviewer**

Use django-storage-swift opencraft-release/ginkgo.1

---

conf/locale/en/LC_MESSAGES/django.po
conf/locale/he/LC_MESSAGES/django.po
lms/djangoapps/instructor/views/api.py
lms/djangoapps/instructor_analytics/csvs.py
lms/djangoapps/instructor_task/tasks_helper/utils.py
lms/djangoapps/instructor_task/tests/test_tasks_helper.py
lms/envs/common.py
lms/static/sass/course/instructor/_instructor_2.scss
lms/templates/instructor/instructor_dashboard_2/data_download.html
lms/templates/instructor/instructor_dashboard_2/instructor_dashboard_2.html
lms/templates/instructor/instructor_dashboard_2/sensitive_data_download_msg.txt

Set the flag `ENABLE_SENSITIVE_DATA_MSG_ON_DASHBOARD` to `True` in `site_configuration` or in `settings.FEATURES`
cc @pomegranited

(CAM-11 & CAM-12) Downloaded data is sensitive

---

lms/templates/courseware/course_about.html

(cherry picked from commit b8e384e5e8d0c87eb3f600cec12975543e64d28b)
See PR upstream. https://github.com/edx/edx-platform/pull/17543
Required to add an extra „Enquire now“ button. (https://github.com/open-craft/edx-theme/pull/33)

Add template block to allow redefining the details section in themes

---

common/lib/xmodule/xmodule/course_module.py
common/test/acceptance/pages/studio/settings_advanced.py

This adds a CourseFields field to store arbitrary fields.
Upstream PR: https://github.com/edx/edx-platform/pull/17699
**JIRA tickets**: None
**Discussions**: None
**Screenshots**: None
**Sandbox URL**: see the theme PR
1. Test it in conjunction with the Pearson theme settings PR („program code, institution hidden“): https://github.com/open-craft/edx-theme/pull/38/
**Reviewers**
**Author concerns**: None
**Settings**: None

Add CourseFields.other_course_settings to store custom fields

---

cms/__init__.py
lms/__init__.py
lms/monkey_patch/__init__.py
lms/monkey_patch/django.py

Applying this patch: https://github.com/cfpb/cfgov-refresh/commit/7616c6bb3ec310e72b1c9538d9176ba61a73ebd3#diff-dffeeb550eca65d51cda43001ff38d4d to lms and cms.
JIRA Ticket: OC-4097
Testing instructions:
Try running migrations without this patch, it should take a lot of time on the step "Rendering models states", if you switch to the version with the patch that step should be quick and migrations should run much faster... without eating that much memory.
[Reviewer]
Uman

Fix for migrations running slow on Django 1.8

---

cms/djangoapps/contentstore/management/commands/import.py
common/djangoapps/util/sandboxing.py
common/lib/xmodule/xmodule/modulestore/tests/test_xml_importer.py
common/lib/xmodule/xmodule/modulestore/xml_importer.py
common/lib/xmodule/xmodule/tests/test_import_static.py
lms/djangoapps/dashboard/git_import.py
lms/envs/aws.py

Cherry-picked from [commit 8476f1946302dd2a9eb8ae7efee03f2294bc787c](https://github.com/edx/edx-platform/commit/8476f1946302dd2a9eb8ae7efee03f2294bc787c#diff-9c3ead93451851d6990b6846cdd00120)
This change allows us to import courses with Unicode file names inside them. Otherwise it fails (`UnicodeDecodeError: 'ascii' codec can't decode byte 0xd7 in position 1: ordinal not in range(128)`).
**JIRA tickets**: None
**Discussions**: None
**Screenshots**: None
**Sandbox URL**: https://daniel-campus-sandbox.opencraft.hosting/
1. Register at https://daniel-campus-sandbox.opencraft.hosting/ and log in to https://studio-daniel-campus-sandbox.opencraft.hosting/
2  Create empty course, and import a course file which has Unicode …

Fix Unicode course import. (Enabled python code lib import with GIT_IMPORT_STATIC set to False)

---

openedx/features/course_experience/views/course_home.py

Fixed access to course handouts by `anonymous` user.
**JIRA tickets**: https://tasks.opencraft.com/browse/SE-332
`---------------------- Before ----------------------`
`---------------------- After ----------------------`
**Sandbox URL**: http://145.239.12.102/
1. Logout
2. [Visit course url](http://145.239.12.102/courses/course-v1:edX+DemoX+Demo_Course/course/)
3. You should not be able to view/download course handouts
**Author notes and concerns**: do i need also to hide `Important Course Dates` ? In that way it will be consistent, because we aren't showing `Course Tools` and `Course Handouts` but showing `Important Course Dates` 
**Reviewers**: @pomegranited

SE-332 Cloudera: Course page with course handouts viewable by anyone, no login

---

manage.py

This PR contains a fix for the precedence of loading Django settings when running management commands. This is useful when running managements commands in any environment, not needing to set the `--settings` flag as long as the correct environment variables are present.
The manage.py script defaults to using `lms.envs.docker_devstack`, and this can only be overridden by either passing the command-line switch or setting the `DJANGO_SETTINGS_MODULE` environment variable. The problem with this approach is that it depends on whether we want to run an `lms` or `cms` command. The scripts `lms.sh` and `cms.sh` take care of this and set the variable correctly for the respective service variant when using the devstack, but that doesn't happen on a production environment.
This fix implements the …

BB-674 - Change Django's configuration precedence in manage.py

---

manage.py

This PR contains a fix for the precedence of loading Django settings when running management commands. This is useful when running managements commands in any environment, not needing to set the `--settings` flag as long as the correct environment variables are present.
The manage.py script defaults to using `lms.envs.docker_devstack`, and this can only be overridden by either passing the command-line switch or setting the `DJANGO_SETTINGS_MODULE` environment variable. The problem with this approach is that it depends on whether we want to run an `lms` or `cms` command. The scripts `lms.sh` and `cms.sh` take care of this and set the variable correctly for the respective service variant when using the devstack, but that doesn't happen on a production environment.
This fix implements the …

BB-674 - Change Django's configuration precedence in manage.py 

---

cms/djangoapps/bundles/urls.py
cms/djangoapps/bundles/views.py
openedx/core/lib/xblock_runtime/blockstore_kvs.py
openedx/core/lib/xblock_runtime/runtime.py
openedx/core/lib/xblock_runtime/utils.py

This adds handler support to the prototype Blockstore-based XBlock runtime being developed in the https://github.com/edx/edx-platform/pull/19136 feature branch.
**TODO**:
**Test Instructions**:
* Follow the instructions at https://github.com/edx/edx-platform/pull/19136 to import a Drag and Drop XBlock into Blockstore
* View the XBlock's student_view JSON, e.g. at http://localhost:18010/api/bundles/v0/block/gblock-v1:ec2566b7-e618-429b-8d97-b3ded042b862:drag-and-drop-v2:971aadaaaa5a4886b37fee3ced711b30/ (may need to change the IDs to match your local setup)
* Open the JS console and call the publish_event handler using the code below (change the block ID):
```
blockId = 'gblock-v1:ec2566b7-e618-429b-8d97-b3ded042b862:drag-and-drop-v2:971aadaaaa5a4886b37fee3ced711b30';
secureUrl = (await …
```

Implement XBlock Handlers in Blockstore Prototype Runtime

---

openedx/core/djangoapps/oauth_dispatch/management/commands/create_dot_application.py
openedx/core/djangoapps/oauth_dispatch/management/commands/tests/test_create_dot_application.py

This is a cherry pick from master that allow us to set client id and secret from the playbooks.
Original commit:
Allows for the creation of public applications, and the passing of the
client_id or client_secret to the command, e.g. from a configuration playbook.
1. Pull this branch on your `hawthorn` devstack.
2. Check that the `create_dot_application` management comments supports the arguments `client_id` and `client_secret`.
3. Create OAuth credentials using:
```
./manage.py lms create_dot_application retirement_service_worker retirement_service_worker@example.com --client-id TEST-CLIENT-ID --client-secret TEST-CLIENT-SECRET
```
4. Check that the correct credentials were created [here](http://edx.devstack.lms:18000/admin/oauth2_provider/application/).
Note: …

BB-987: Cherry pick management command changes

---

lms/envs/production.py

This PR adds a way of changing the default build profile used by RequireJS via `lms.env.json`. 
This is useful when using custom themes that need extra functionality added to pages and elements that use require.js.
**Testing instructions:**
1. Pull this branch into your devstack.
2. Copy and paste `build.js` to a folder inside a theme custom theme (doesn't matter which)
3. Modify your `lms.env.json` and add:
```
"REQUIRE_BUILD_PROFILE": "path-to-theme/lms/build.js",
```
4. Restart LMS
5. Rebuild your LMS assets:
```
make lms-shell
paver update_assets
```
6. Check that the variable was correctly loaded on django settings:
```
make lms-shell
./manage.py lms shell
>>> from django.conf import settings
>>> settings.REQUIRE_BUILD_PROFILE
u'path-to-theme/lms/build.js'  # Should output this
``` …

BB-1156 Backport: Enable changing the build profile used by RequireJS

---

requirements/edx/base.in
requirements/edx/base.txt
requirements/edx/development.txt
requirements/edx/testing.txt

Bumps version of edx-completion to 1.0.3.
* Addresses JWT and inactive user auth issues between completion API and iOS app
* Bumps `edx-drf-extensions` and `XBlock` dependencies to remain compatible with completion, Ginkgo + Hawthorn
**JIRA tickets**: SE-985
**Discussions**: See https://github.com/edx-solutions/edx-platform/pull/1421
**Sandbox URL**: sandbox is being provisioned.
* LMS: https://pr165.sandbox.opencraft.hosting/
* Studio: https://studio.pr165.sandbox.opencraft.hosting/
Set up edxapp server:
1. Enable mobile REST API (see `FEATURES` below).
1. Enable completion waffle switch: [completion.enable_completion_tracking](https://pr165.sandbox.opencraft.hosting/admin/waffle/switch/2/change/)
1. Create a public, mobile [OAuth2 …

SE-985 Backport mobile auth completion fix to Hawthorn

---

openedx/core/djangoapps/schedules/management/commands/__init__.py
openedx/core/djangoapps/schedules/management/commands/send_course_update.py
openedx/core/djangoapps/schedules/management/commands/tests/test_send_email_base_command.py

Cherry-picks the change from https://github.com/edx/edx-platform/pull/19906 into our ironwood release branch.
**Sandbox URL**: sandbox is being provisioned.
* LMS: https://pr169.sandbox.stage.opencraft.hosting/
* Studio: https://studio.pr169.sandbox.stage.opencraft.hosting/
Sandbox `staff` user has superuser privileges.
1. [Enable the creation](https://pr169.sandbox.stage.opencraft.hosting/admin/waffle/) and [scheduling](https://pr169.sandbox.stage.opencraft.hosting/admin/schedules/scheduleconfig/) of course highlights in Django Admin.
1. [Create a self-paced course with weekly course highlights added](https://studio.pr169.sandbox.stage.opencraft.hosting/course/course-v1:OpenCraft+CH+2019_1) to at least section 11 .
1. Register, activate, …

SE-752 Adds duration argument to send_course_update management command.

---

openedx/core/djangoapps/user_api/api.py
openedx/core/djangoapps/user_api/helpers.py
openedx/core/djangoapps/user_api/tests/test_views.py

This PR makes all the registration fields except the username, uneditable for user when using cloudera's SSO.
See upstream PR https://github.com/edx/edx-platform/pull/20957
**JIRA**: SE-1017
**Testing Instructions**:
1. Check the cloudera SSO provider config in the django admin page and ensure the option `send to registration form` flag is enabled.
2. Add the registration field names that you'd like to make read-only under the advanced settings like:
```
{"PROVIDER_READ_ONLY_FIELDS": ["email", "name"]}
```
3. Go to the dashboard page and login with SSO credentials.
4. Verify that all the fields except username, is not editable by the user.
**Reviewers:**
@pomegranited

SE-1017 Disable all registration fields except username

---

lms/templates/courseware/progress_graph.js

Description
---------------
There's an issue that when the screen size is changed after the progress bar is rendered the y-axis values move and overlap the graph or end up off the screen.
The issue here is that the graph is drawn using d3 and d3 fixes nodes to a specific x and y value. The y-axis values are fixed using the `left` css attribute. When the screen changes the `left` value keeps the same and it ends up being somewhere different.
The fix is to make the parent div to have a fixed width which is going to be the width of the screen (or really wherever it's rendered, could be another div) and that width will not change if the screen size is changed.

Fix the progress graph y-axis - window resize formatting problem in Ironwood

---

lms/djangoapps/courseware/views/views.py

This fixes the errors when the API client is configured to require
a referer for all the requests.

[BB-1637] Pass the referer from the client to the YouTube API

---

common/djangoapps/third_party_auth/__init__.py
common/djangoapps/third_party_auth/pipeline.py

Upstream code has made this patch obsolete, so we are reverting this change to remove the code drift in our branch.
1. Verify that the testing process described in [SE-1069](https://tasks.opencraft.com/browse/SE-1069) was sufficient to justify removing this code change.
1. Check that the two files modified here now match upstream [`open-release/ironwood.2`](https://github.com/edx/edx-platform/tree/open-release/ironwood.2).
**Reviewers**

SE-1069 Reverts addition of third_party_auth.ENABLE_OKTA_AUTH_FIX

---

openedx/core/djangoapps/heartbeat/views.py

Adds error logging for failed heartbeat checks, since our monitoring only reports the 503 status.
**JIRA issue** [SE-1773](https://tasks.opencraft.com/browse/SE-1773)
This change is deployed to the Ocim stage server `145.239.14.32` ([Ocim instance, Appserver 20](https://stage.console.opencraft.com/instance/4230/edx-appserver/1496/)).  Since there are two running hosts for that server which do not share a memcache, the celery healthcheck fails about 50% of the time.  But you're unable to reproduce a failure, the you can suspend the forums service on one of the servers to force a failure there.
1. Shell into `145.239.14.32`  and watch the `/edx/var/log/lms/edx.log`.
1. Refresh http://145.239.14.32/heartbeat?extended until you get a failure.
1. Note the log message …

SE-1773 Logs failed heartbeat checks

---

common/lib/xmodule/xmodule/contentstore/mongo.py
common/lib/xmodule/xmodule/course_metadata_utils.py
common/lib/xmodule/xmodule/modulestore/mongo/base.py
common/lib/xmodule/xmodule/modulestore/mongo/draft.py
common/lib/xmodule/xmodule/modulestore/split_mongo/mongo_connection.py
common/lib/xmodule/xmodule/modulestore/split_mongo/split.py
common/lib/xmodule/xmodule/modulestore/tests/factories.py
common/lib/xmodule/xmodule/modulestore/tests/test_mongo_call_count.py
common/lib/xmodule/xmodule/modulestore/tests/test_split_mongo_mongo_connection.py
common/lib/xmodule/xmodule/mongo_utils.py
lms/djangoapps/dashboard/git_import.py
lms/djangoapps/dashboard/sysadmin.py
requirements/edx/base.txt
requirements/edx/development.txt
requirements/edx/paver.in
requirements/edx/paver.txt
requirements/edx/testing.txt

This commit upgrades the version of pymongo from 2.x to 3.x, removing usages to deprecated functions usage and fixing tests where necessary.
This version of pymongo supports MongoDB 2.x all the way up to 4.2, and this ensures that the platform will be able to run on a supported MongoDB version in the next release.
(cherry picked from commit 9b69d5a62684dc3d9d86b7e71081bebd432bd7d9)
See discussion and testing instructions on upstream ticket https://github.com/edx/edx-platform/pull/21197.
**Sandboxes:** 
Mongo 3.2: https://console.opencraft.com/instance/17030/
Mongo 3.6: https://console.opencraft.com/instance/17070/
Mongo 4.0: https://console.opencraft.com/instance/17080/
**Reviewers:**

BB-1744: Bump pymongo version and fix course export issue

---

cms/envs/production.py
lms/envs/production.py

Previously this was causing a NameError, because it was attempting to
use ENV_TOKENS before it was defined.
This issue was introduced in https://github.com/open-craft/edx-platform/pull/198 where unfortunately it didn't get tested thoroughly (turns out ironwood and master differ enough in this case that while the patch backported cleanly, it was no longer valid). :(
- launch a production sandbox or provision a devstack with this branch ([this sandbox](https://console.opencraft.com/instance/17390/) is being provisioned from this branch)
- verify that it provisions successfully and that BROKER_HEARTBEAT and BROKER_HEARTBEAT_CHECKRATE are set as expected.

SE-1541 Move block to where ENV_TOKENS is defined

---

common/lib/xmodule/xmodule/js/src/video/02_html5_hls_video.js

This PR fixes the issue with autoadvance noted on cloudera courses which are HLS videos.
**Upstream PR:** [#22539](https://github.com/edx/edx-platform/pull/22539)
1. Create a course with consecutive units containing videos. Add a m3u8 (HLS) video in the second unit.
2. Ensure "ENABLE_AUTOADVANCE_VIDEOS" is set to true in lms.env.json file.
3. Set the enable video auto-advance flag in Advanced settings in studio.
4. Enroll into the course from lms and start course.
5. Verify that at the end of the first video, the next unit is loaded automatically and the video starts playing.
**Reviewers:**

SE-1908 Fix for autoadvance issue with hls videos

---

common/djangoapps/student/admin.py
common/djangoapps/student/tests/test_admin_views.py

Reverts early-merged changes from b0cf5d57 and backports the upstreamed ones from 0e85af8.
1. Login as a superuser or a user that has access to `/admin`.
2. Go to `admin/waffle/switch/` and create a switch with the name `student.courseenrollment_admin` in case it's not there already.
3. Go to `admin/student/courseenrollment/`.
4. Click on any of the row IDs.
5. Uncheck the `active` box and save it.
**The course enrollment should be updated without any errors.**

[BB-1933] Backport CourseEnrollmentForm changes

---

cms/djangoapps/contentstore/views/helpers.py
common/djangoapps/student/models.py
common/djangoapps/student/views/management.py
lms/djangoapps/courseware/url_helpers.py
openedx/core/djangoapps/content/block_structure/store.py

This PR fixes a unicode error that is noticed when creating a course in a non-english language.
**JIRA tickets:** [SE-1981](https://tasks.opencraft.com/browse/SE-1981)
**Dependencies:** None
**Sandbox URL:** TBD
1. Enable a unicode language (say ja-jp) in the instance config.
2. Create a new course in the unicode language (make sure browser preference is set to the language as well) from Studio.
3. Verify that the course gets created successfully and user is able to enroll into it.
**Reviewers:**

Fix unicode error

---

lms/djangoapps/mobile_api/testutils.py
lms/djangoapps/mobile_api/users/tests.py
lms/djangoapps/mobile_api/users/views.py

Moves user_logged_in signal to UserDetail.get so that it's triggered on initial app login and when app is re-launched.
cherry picked from commit 3b3c7bc07a61deab607967b67e201f9d3e09b74e, cf https://github.com/edx/edx-platform/pull/22999
I believe the testing we did for the upstream PR is sufficient here.  So it's just a straight backport cherry-pick, and there were no conflicts.
**Reviewer**

SE-2092 Send user_logged_in when Mobile API user detail requested

---

lms/djangoapps/courseware/views/views.py
openedx/features/course_experience/tests/views/test_course_home.py
openedx/features/course_experience/views/course_home_messages.py

This commit updates the Info messages on the course page to display
more informative messages to the user. Specifically, messages for Public
and Invitation-only courses.
(cherry picked from commit c6f87d49f28782dd84d9c07aecfbce19814b0892)

Show Enroll links on public courses only if self-enrollment is allowed

---

cms/envs/common.py
cms/urls.py
common/djangoapps/student/admin.py
lms/envs/common.py
lms/urls.py

This was previously disabled because changing another user's password is
both not usually recommended and bypasses password policy. Here, we add
a feature flag (`ENABLE_CHANGE_USER_PASSWORD_ADMIN`) to allow
re-enabling this password change form. This allows continued use of this
functionality by clients that require it.
(cherry picked from commit 39de23c666d1a6a6313129709ea71832ef12f71b)
---
See upstream PR https://github.com/edx/edx-platform/pull/21616 for test instructions. This is identical apart from being based on our ironwood branch instead of master.
**Reviewer**:

SE-1496 (backport) Add flag to enable password change form in admin

---

openedx/core/djangoapps/content/block_structure/store.py

This fixes an issue related to the relationship between https://github.com/open-craft/edx-platform/pull/205 and https://github.com/open-craft/edx-platform/pull/212. Because of a bad merge or something, the unicode handling in a particular code block was messed up (attempting to reference `six.text_type` when it was imported as `text_type`, returning string instead of text_type). 
-    LMS: https://se-2481.sandbox.opencraft.hosting/
-    Studio: https://studio.se-2481.sandbox.opencraft.hosting/
- https://console.opencraft.com/instance/18700/edx-appserver/12336/
**Merge deadline**: ASAP - currently grade reports are broken for production instances
- ssh into the appserver and `sudo tail -f /edx/var/log/supervisor/lms_*`
- log in to the instance as …

Fix grade reports invalid reference to six

---

lms/templates/instructor/instructor_dashboard_2/certificates.html

See https://github.com/edx/edx-platform/pull/23735 - this is the ironwood backport of that PR

SE-2483 unhide certificates toggle ironwood

---

common/djangoapps/third_party_auth/pipeline.py
common/djangoapps/third_party_auth/strategy.py

This PR cherry-picks an existing ginkgo customization code drift required for SSO to work and also adds `gender` to the list of fields synced by the platform from SSO user data.
* Deploy this branch.
* Also deploy the changes to the `edx-oauth-client` from the corresponding PR branch.
* Create an account on the Drupal frontend, log in and navigate to the LMS.
* Verify that the user is logged into the LMS and all the user data is copied properly to the corresponding fields in the `User` model and the `UserProfile` model.

[BB-1840] Ironwood SSO fixes

---

lms/djangoapps/course_api/blocks/serializers.py
lms/djangoapps/course_api/blocks/tests/test_views.py
lms/djangoapps/course_api/blocks/transformers/blocks_api.py
lms/djangoapps/course_api/blocks/transformers/extra_fields.py
lms/djangoapps/course_api/blocks/transformers/tests/test_extra_fields.py
lms/djangoapps/course_api/blocks/views.py
lms/envs/common.py
lms/envs/test.py

Adds custom extra fields to Course Blocks API by specifying field names and the block type in the `COURSE_BLOCKS_API_EXTRA_FIELDS` LMS Settings variable.
`COURSE_BLOCKS_API_EXTRA_FIELDS` is a list of tuples. Each tuple contains two values, respectively:
1. Block Type (values separated by commas (,) or `*`)
2. Requested Field Name (string)
This PR backports the changes made in edx/edx-platform#24586 to Juniper.2
**JIRA tickets**: SE-2968
**Upstream PR**: edx/edx-platform#24586
**Sandbox URL**: https://extrafields-backport.opencraft.hosting/
- Read through the code
- Run necessary tests and quality tests
- `paver test_system`
- `paver run_quality`
- Use this endpoint to test out API
1. Login to the instance with the default `staff` credentials
1. Navigate to [this …

[SE-2968] Adds Custom Extra Fields to Course Blocks API through LMS Settings - Backported to Juniper

---

cms/static/js/views/video/translations_editor.js

Fixes issue introduced by https://github.com/open-craft/edx-platform/pull/237 code ported from upstream.
**Screenshots**
Before this fix:
After this fix:
**Sandbox**
* LMS: https://se3126-juniper.sandbox.opencraft.hosting/
* Studio: https://studio.se3126-juniper.sandbox.opencraft.hosting/
1. In Studio, add a Video unit, and edit the unit.
1. Under Basic, locate "Default Timed Transcript" and click the "Import YouTube Transcript" button, then "Download Transcript for Editing", to download an `.srt` file.
1. Change to the Advanced tab, and scroll down to "Transcript languages".
1. Add a language (any language), and upload the `.srt` file downloaded in the previous step.
1. Ensure that you can save the unit.
1. Re-edit the unit and ensure the `.srt` file you uploaded …

SE-3126 Fix issue caused by XSS fix in Video > Advanced > Transcript Languages

---

lms/djangoapps/courseware/views/views.py

Fix is based on upstream's edx/edx-platform#24731 - Commit Hash c2033f9667b07b3eab3bde9410692a27ad615bd8
**JIRA tickets**: SE-3199
**Discussions**: https://chat.opencraft.com/opencraft/pl/9cwgciag63gquxm3jmh6868ekr
Sandbox Instance: https://manage.opencraft.com/instance/20950/
- Apply [Manual Instance Checklist](https://gitlab.com/opencraft/documentation/private/blob/master/checklists/manual_instance_test.md) on the Sandbox
- 1. Setup a Chromeless XBlock
2. Attempt to access the XBlock through the Web
This fix doesn't have to be updated with the next Open edX release since it was merged into upstream 
**Reviewers**

[SE-3199] Specifies default value for Microfrontend Url 

---

cms/static/js/views/baseview.js
cms/static/js/views/license.js
cms/static/js/views/list.js
cms/static/js/views/manage_users_and_roles.js
cms/static/js/views/uploads.js
cms/static/js/views/video/transcripts/message_manager.js
cms/static/js/views/xblock_string_field_editor.js
cms/templates/js/course_info_handouts.underscore
cms/templates/js/grading-editor.underscore
cms/templates/js/metadata-string-entry.underscore
cms/templates/js/section-name-edit.underscore
cms/templates/js/signatory-actions.underscore
cms/templates/js/team-member.underscore
cms/templates/js/video/transcripts/messages/transcripts-import.underscore
cms/templates/js/video/transcripts/messages/transcripts-not-found.underscore
cms/templates/js/video/transcripts/messages/transcripts-replace.underscore
cms/templates/js/video/transcripts/messages/transcripts-uploaded.underscore
cms/templates/js/video/transcripts/messages/transcripts-use-existing.underscore
cms/templates/js/xblock-outline.underscore

This PR contains cherry-picked commits from:
https://github.com/edx/edx-platform/pull/24877
https://github.com/edx/edx-platform/pull/24881

BB-2941 Latest batch of XSS fixes

---

common/lib/xmodule/xmodule/static_content.py
openedx/core/djangoapps/theming/storage.py
openedx/core/storage.py

This PR is aimed at fixing the issue with asset compilation for themes in Juniper is resulting in differently-named files.
**JIRA tickets:** [SE-3149](https://tasks.opencraft.com/browse/SE-3149)
**Sandbox:** https://manage.opencraft.com/instance/21210/
1. Deploy ocim instance with custom theme using this branch. You can check the sandbox created - https://manage.opencraft.com/instance/21210/
2. Spawn new appserver and check the css files generated in /edx/var/edxapp/staticfiles/css.
3. Run `paver update_assets` command and recheck that no new css files are generated in /edx/var/edxapp/staticfiles/css.
4. Spawn multiple appservers and add to load-balancer. Verify that the assets are getting loaded correctly.
**Reviewers:**

[SE-3149] Fix the theme compilation issue in juniper

---

lms/envs/common.py
lms/envs/production.py

This change introduces a way to help filling form, with the constant we
can specify the order of the countries that should come first. This will
reduce the chance of committing a mistake while filling form.
**JIRA tickets**: [BB-2924](https://tasks.opencraft.com/browse/BB-2924)
None
1. Pull the changes from this branch
2. Start `LMS` by `make dev.up.lms`
3. Drop in the `LMS` shell with `make dev.shell.lms`
4. Open the `lms.yml` file `vim /edx/etc/lms.yml` in `LMS` shell
5. Add 
```
DJANGO_COUNTRIES_FIRST: ['SA', 'BH', 'QA', 'KW', 'AE', 'OM', 'YE', 'JO', 'IQ', 'ER', 'IL', 'IR', 'PS', 'EG', 'SY', 'LB', 'DJ', 'CY', 'ET', 'SD', 'AM']
```
in `lms.yml` file
6. Restart the server `make lms-restart`
4. Go to the register page, and …

[BB-2924] Added a constant to help modify countries list in drop-down

---

common/lib/xmodule/xmodule/js/spec/video/completion_spec.js
common/lib/xmodule/xmodule/js/spec/video/video_events_plugin_spec.js
common/lib/xmodule/xmodule/js/src/video/09_completion.js
common/lib/xmodule/xmodule/js/src/video/09_events_plugin.js

This pull request is about adding new events to video player about watching progression.
Upstream pull request: edx/edx-platform#25038
**JIRA tickets**: [SE-3248](https://tasks.opencraft.com/browse/SE-3248)
- [LMS](https://pr25038.sandbox.opencraft.hosting/)
- [Studio](https://studio.pr25038.sandbox.opencraft.hosting/)
*Sandbox is being provisioned.*
1. Create a video unit
2. Enroll into the course
3. Open the web inspector (network panel)
4. Watch the video
5. Check that events are being fired every decades
**Reviewers**

[SE-3248] Add progress_video event and update tests

---

common/lib/xmodule/xmodule/html_module.py

This is required to stop get_course_about_section
html content from using the edxnotes version of
get_html, which injects the edxnotes html into it.
We don't want this injected into the html here,
because these are snippets meant to be displayed
in original form on the course about page.
See https://github.com/edx/edx-platform/pull/24930 for more details and test instructions. This PR simply backports that to our juniper.3 release branch.

SE-3243 Use original get_html for AboutBlock

---

lms/djangoapps/dashboard/sysadmin.py

This fixes the error thrown when trying to download the list of all
users, staff and instructors from the Sysadmin dashboard
Reference: [unicodecsv README file](https://github.com/jdunck/python-unicodecsv/blob/master/README.rst)
* In the Juniper devstack, enable the `Sysadmin dashboard` by setting the `ENABLE_SYSADMIN_DASHBOARD` feature flag to `true` in `/edx/etc/lms.yml` and restart the LMS.
* Log in to the LMS as a user with superuser permissions.
* Navigate to the Sysadmin dashboard by clicking on the link in the top nav bar.
* In the `Users` section, try to download a list of all the users in CSV file format. An exception complaining `TypeError: string argument expected, got 'bytes'` will be thrown.
* In the `Staffing and enrollment` section, try downloading …

[BB-3057] Use BytesIO as unicodecsv expects a bytestream, not unicode

---

common/lib/xmodule/xmodule/js/spec/video/completion_spec.js
common/lib/xmodule/xmodule/js/src/video/09_completion.js

This is a follow-up merge request (previous one #256) in order to send video progress every 5 percents instead of 10 as Autodesk.
Upstream merge request: edx/edx-platform#25038
We will need to cherry-pick this change into the Autodesk special branch as well.
**JIRA tickets**: [SE-3248](https://tasks.opencraft.com/browse/SE-3248)
- [LMS](https://autodesk-geoffrey.opencraft.hosting)
- [Studio](https://studio.autodesk-geoffrey.opencraft.hosting)
*Sandbox is being provisioned.*
1. Create a video unit
2. Enroll into the course
3. Open the web inspector (network panel)
4. Watch the video
5. Check that events are being fired every decades
**Reviewers**

[SE-3248] Update video progression events to 5-range instead of decade

---

common/lib/xmodule/xmodule/js/spec/video/completion_spec.js
common/lib/xmodule/xmodule/js/src/video/09_completion.js

This pull request is about back porting the change to video player events (every 5 percents instead of 10) to the Autodesk branch. (open-craft/edx-platform#266)
**JIRA tickets**: [SE-3248](https://tasks.opencraft.com/browse/SE-3248)
**Reviewers**

[SE-3248] Backport video player events to Autodesk branch

---

common/lib/xmodule/xmodule/static_content.py

There is a small bug that started happening in Juniper related to webpack's cached files, where the hashes were not consistent on different machines and would change on every assets update. Accordingly, this caused 404 errors with multiple instances and load balancers, which made the Studio and LMS unusable.
Some examples of the Studio and LMS being unusable:
- Studio would load but no courses would be populated
- LMS would load but no units would load in
- Any functionality relying on JavaScript became unusable (such as XBlocks and XModules)
**JIRA tickets**: SE-3401
- **LMS**: https://pr264.sandbox.stage.opencraft.hosting/
- **Studio**: https://studio.pr264.sandbox.stage.opencraft.hosting/
1. Spawn multiple instances and add to load-balancer. …

[SE-3401] Sorts XModules and XBlocks JS Bundles to Make Webpack Hashes Consistent

---

cms/static/js/views/uploads.js

This cherry picks a fix from `open-release/juniper.master` to fix file upload issues on the studio.
When selecting a file for uploading to the Course Card image, or the Certificate Signatory Editor view, instead of showing the file it shows "[object HTMLInputElement]", and the file upload fails. This cherry picked fix from upstream fixes the issue.
**JIRA tickets**: Fixes SE-3472.
Without this fix after using the file selection dialog: 
1. Attempt to change Course Card Image in the studio to test the file upload dialog
2. Ensure that it correctly shows the path and the upload works
**Reviewers**

Cherry pick fix for Studio file upload issues

---

common/djangoapps/third_party_auth/decorators.py

This enables `X-Frame-Options` for the Login and Registration Forms on Autodesk instances. This is because using LTI third party auth is not an option.
This change targets the `x_frame_option` because it hasn't changed since 5 years (check git blame).
**JIRA tickets**: SE-3437
1. This is a temporary fix that needs to be replaced with a better solution later on.
**Reviewers**

[SE-3437] Changes Default Value of X_FRAME_OPTION for Login and Registration Form

---

cms/static/js/views/uploads.js
cms/templates/js/group-configuration-details.underscore
cms/templates/js/maintenance/force-published-course-response.underscore
cms/templates/js/mock/mock-xmodule-editor.underscore
cms/templates/js/publish-editor.underscore
cms/templates/js/unit-outline.underscore
cms/templates/js/video/transcripts/file-upload.underscore
cms/templates/js/xblock-validation-messages.underscore

This backports #272 and XSS fixes from #273 to Ironwood.
1. Go to [course settings](http://localhost:18010/settings/details/course-v1:edX+DemoX+Demo_Course) and check that uploading a new Course Card Image works.

 [BB-3145] Backport patches from Juniper

---

lms/djangoapps/support/static/support/js/views/certificates.js
lms/static/js/certificates/views/certificate_whitelist.js
lms/static/js/courseware/certificates_api.js
lms/static/js/discovery/views/course_card.js
lms/static/js/discovery/views/facet.js
lms/static/js/edxnotes/views/note_group.js
lms/static/js/edxnotes/views/note_item.js
lms/static/js/edxnotes/views/tabs/course_structure.js
lms/static/js/edxnotes/views/tabs/recent_activity.js
lms/static/js/groups/views/course_cohort_settings_notification.js
lms/static/js/student_account/views/account_section_view.js
lms/static/js/verify_student/views/error_view.js

This cherry-picks security updates and fixes from https://github.com/edx/edx-platform/pull/25786 which are the same shared as patch for the 2020-12-03 XSS security fixes.
- Make sure the changes reflect the patch shared from edx
- Check Instance is working correctly: https://pr297.sandbox.stage.opencraft.hosting/ (follow instance checklist)
**Reviewers**

[SE-3745]: Cherry picks 2020-12-03 XSS security fixes from upstream

---

common/djangoapps/third_party_auth/decorators.py

Update the `X-Frame-Options` default value for login and registration forms to the existing `EDXAPP_X_FRAME_OPTIONS` environment settings to match the default setting across the whole platform. 
**JIRA tickets**: SE-3437, [OSPR-5053](https://openedx.atlassian.net/browse/OSPR-5053)
**Upstream PR**: https://github.com/edx/edx-platform/pull/25338
- **LMS**: https://pr25338.sandbox.opencraft.hosting/
- **Studio**: https://studio.pr25338.sandbox.opencraft.hosting/
1. Send a request to the Login page with a specific `Referer: customhostname.com` header
2. Verify that the response header contains `X-Frame-Options: ALLOW`
**Reviewers**
**Settings**
```yaml
EDXAPP_LMS_ENV_EXTRA:
X_FRAME_ALLOW_WHITELISTED_REFERERS: [
'customhostname.com'
]
```

[SE-3437] Sets default X-Frame-Options for login and registration forms to environment setting

---

common/djangoapps/enrollment/serializers.py

This updates the format of the grading key from the CourseEnrollmentSerializer to remove the unnecessary wrapping in a list since it will always be a single item.
**JIRA tickets**: BB-3440
**Merge deadline**: Promptly
Check the format of the grading key under the course enrollments API and ensure it's not a list: http://localhost:18000/api/enrollment/v1/enrollment?user=honor
1. The final format of upstream changes this endpoint is still under discussion on https://github.com/edx/edx-platform/pull/20948/files
**Reviewers**

Switch grading data format in CourseEnrollmentSerializer

---

cms/templates/widgets/footer.html
lms/djangoapps/branding/tests/test_api.py
lms/envs/common.py
lms/templates/footer.html
themes/edx.org/lms/templates/footer.html
themes/red-theme/lms/templates/footer.html

Cherry picked from https://github.com/edx/edx-platform/pull/25898
- verify that this cleanly backports the referenced pull request
- check an instance or your devstack with this branch, and verify that the new logos are displayed
**Author notes**:
- This also updates the http open.edx.org links to https, matching upstream.  Did this because there was a merge conflict on those lines, and updating to https made sense.
**Reviewers**:

SE-3690 Update the Open edX logo urls (backport to opencraft-release/juniper.3)

---

lms/djangoapps/support/static/support/js/views/certificates.js
lms/static/js/certificates/views/certificate_whitelist.js
lms/static/js/courseware/certificates_api.js
lms/static/js/discovery/views/course_card.js
lms/static/js/discovery/views/facet.js
lms/static/js/edxnotes/views/note_group.js
lms/static/js/edxnotes/views/note_item.js
lms/static/js/edxnotes/views/tabs/course_structure.js
lms/static/js/edxnotes/views/tabs/recent_activity.js
lms/static/js/groups/views/course_cohort_settings_notification.js
lms/static/js/student_account/views/account_section_view.js
lms/static/js/verify_student/views/error_view.js

Security fixes.
**JIRA tickets**:
- [BB-3349](https://tasks.opencraft.com/browse/BB-3349)
**Sandboxes**:
https://user-progress.opencraft.hosting/
**Testing instructions**: None.

[BB-3349] IM security fixes

---

common/djangoapps/third_party_auth/config/waffle.py
common/djangoapps/third_party_auth/pipeline.py
common/djangoapps/third_party_auth/settings.py
common/djangoapps/third_party_auth/tests/test_pipeline.py

Currently, in the edX platform, if you try to login with an SSO account using the login form, a username is generated for you based on the email that is used with the SSO provider.
The username is generated using the pipeline `third_party_auth.pipeline.get_username`.
If the username already exists in the platform, you run into a small conflict which sends you back to the login form and requests the following:
It basically requests that you link your edX account and your SSO account.
However, sometimes we would want the edX account and SSO account to be associated by email. There's already a special pipeline available in the platform for that, `third_party_auth.pipeline.associate_by_email_if_login_api`. Sadly, however, it is only available for a certain entry method of authentication, …

[SE-3816] Adds waffle switch to enable third party auth email association

---

cms/envs/common.py
cms/urls.py
lms/djangoapps/gdpr_user_retirement/tests/test_views.py
lms/djangoapps/gdpr_user_retirement/urls.py
lms/djangoapps/gdpr_user_retirement/views.py
lms/envs/common.py
lms/urls.py

This PR adds a new django app to allow the GDPR user retirement via Open edX's REST API. Prior to this the only way to trigger the user retirement was either by the user themself clicking "Delete my account" in the account setting page or via creating a User Retirement request by admin. With these changes, the user retirement process can be triggered using REST API. 
**Jira Tickets:** [SE-3405](https://tasks.opencraft.com/browse/SE-3405)
**Sandbox Url:** TBD
1. Create one or more user accounts that you want to retire. 
2. Go to the django admin -> Django Oauth Toolkit -> Application and copy the client ID and client secret for the `retirement-service-backend-service`.
3. Fetch the access token for the `retirement_user` using the curl command:
```
curl -X POST -d …
```

[SE-3405] Django app to allow user retirement via API

---

cms/envs/common.py
common/lib/xmodule/xmodule/js/src/html/edit.js
pavelib/assets.py
pavelib/paver_tests/test_servers.py
webpack.dev.config.js
webpack.prod.config.js

This makes it possible to install new tinymce plugins through the environment settings.
This PR is responsible for adding the tinymce plugin settings to the tinymce javascript configuration.
**JIRA tickets**: SE-3381, SE-3247
**Dependencies**:
- https://github.com/open-craft/configuration/pull/143
**Upstream Pull Request**:
- https://github.com/edx/edx-platform/pull/25695
- LMS: https://configurable-tinymce-plugins.stage.opencraft.hosting/ 
- Studio: https://studio.configurable-tinymce-plugins.stage.opencraft.hosting/
1. Login to Studio using `staff@example.com`/`edx`
2. Create a new Unit with an HTML Text
3. Make sure that the *ADSK Link* shows in the toolbar
4. Create a link and make sure you can preview it, and see it on the LMS
**Reviewers** …

[SE-3381] Allows adding new tinymce plugins through platform configuration

---

lms/djangoapps/grades/rest_api/v1/gradebook_views.py
lms/djangoapps/grades/rest_api/v1/tests/test_gradebook_views.py

Adds course `grade_cutoffs` to the `/api/grades/v1/gradebook/{course_id}/grading-info`.
**JIRA tickets**: SE-3440
**Upstream Pull Request**: https://github.com/edx/edx-platform/pull/25978
* LMS: https://pr305.sandbox.stage.opencraft.hosting/
* Studio: https://studio.pr305.sandbox.stage.opencraft.hosting/
Run the following function and verify that `grade_cutoffs` is highlighted 😃 
```bash
curl --request POST \
--insecure --url https://pr305.sandbox.stage.opencraft.hosting/oauth2/access_token/ \
--header 'content-type: multipart/form-data;' \
--form grant_type=client_credentials \
--form client_id=LgIomajnBojAT0l65g0jFWxiJTODMejydpoDQDPR \
--form client_secret=qO7Ng8OcwB4tQFbXilDdKIR2uADwfEJNGanSVaDieoq4n39XTExuEpN1qV4yCPiKpyFjKT7y1Awwsy17aCCNNtPl7F …
```

[SE-3440] Adds grade cutoffs to gradebook grading information

---

cms/envs/common.py
common/lib/xmodule/xmodule/js/src/html/edit.js
pavelib/assets.py
pavelib/paver_tests/test_servers.py
webpack.dev.config.js
webpack.prod.config.js

Reverts open-craft/edx-platform#295
The reason behind the revert is that with multiple app servers, the TinyMCE object in the JavaScript code doesn't get sorted by key. This is a huge problem because the changes being upstreamed are already being sorted by key...
So it seems like there's a specific backport that is missing, which should be done before merging this change.
Here's what I'm talking about:
* File 1:
```javascript
var d = {
TINYMCE_ADDITIONAL_PLUGINS: [{
toolbar: !0,
extra_settings: {
linktypes: ["download", "offer"],
orientations: ["Vertical", "Horizontal"],
filetypes: ["PDF", "zip", "Video", "Design"],
styles: ["Primary", "Normal", "Secondary"]
},
name: "adsklink"
}]
}.TINYMCE_ADDITIONAL_PLUGINS;
```
* File 2:
```javascript
var d = {
TINYMCE_ADDITIONAL_PLUGINS: [{
toolbar: …
```

Revert "[SE-3381] Allows adding new tinymce plugins through platform configuration"

---

cms/envs/common.py
common/lib/xmodule/xmodule/js/src/html/edit.js
pavelib/assets.py
pavelib/paver_tests/test_servers.py
webpack.dev.config.js
webpack.prod.config.js

**THIS BACKPORT IS NOT NEEDED FOR KOA**
This re-applies the reverted changes from https://github.com/open-craft/edx-platform/pull/306
---
This makes it possible to install new tinymce plugins through the environment settings.
This PR is responsible for adding the tinymce plugin settings to the tinymce javascript configuration.
**JIRA tickets**: SE-3381, SE-3247
**Dependencies**:
- https://github.com/open-craft/configuration/pull/143
**Upstream Pull Request**:
- https://github.com/edx/edx-platform/pull/25695
**Sandbox**: Upskill STG
1. Login to Studio using `staff@example.com`/`edx`
2. Create a new Unit with an HTML Text
3. Make sure that the *ADSK Link* shows in the toolbar
4. Create a link and make sure you can preview it, and see it on the LMS
1. SSH into each …

[SE-3381] [JUNIPER BACKPORT] Allows adding new tinymce plugins through platform configuration

---

lms/djangoapps/courseware/views/views.py

This PR amends a previous change (fe95b2b94fa25d20b60b2f40533b2bb4a24e7ef1), which allows for configuring where the root URL of a course redirects to.
This older commit ignores the added configuration value if the unified course tab is set, but this removes the option to set the course root redirection when the unified course tab is enabled.
Here we move the check for the `COURSE_HOME_BEHAVIOUR` option from the SiteConfiguration to before checking the unified course tab to allow us to still configure this when the unified course tab is enabled.
**JIRA tickets**: Implements BB-3399
**Discussions**: Discussed on JIRA
1. Set `course_experience.unified_course_tab` flag to true in [your devstack WaffleFlag …

Allow course home behavior configuration to override unified course tab

---

lms/djangoapps/instructor/enrollment.py
openedx/core/djangoapps/ace_common/template_context.py
openedx/core/djangoapps/site_configuration/helpers.py
openedx/core/djangoapps/site_configuration/tests/test_helpers.py

When using multiple sites, there is not much room for custom email per site. To achieve customization per-site basis, this PR puts Site Configuration in the context while rendering email templates.
**JIRA tickets**: https://tasks.opencraft.com/browse/BB-3624
~~**Discussions**:~~
**Screenshots**:  N/A
1. Pull this PR on local devstack
2. Set ``PLATFORM_NAME`` in default site configuration from Django admin.
3. From the login page ask for password reset and check password reset email has platform name from the site configuration.
4. From the instructor dashboard enroll a user and check if enroll request email has the platform name from the site configuration. …

[BB-3624] Add Site Configuration in email context

---

common/djangoapps/student/helpers.py

This PR adds the `mailing_address` and `site_configuration_values` added in https://github.com/open-craft/edx-platform/pull/315 to the `generate_activation_email_context()` function as well so that they can be used in the activation emails.

[BB-3624] Add site configuration in activation email context

---

common/djangoapps/third_party_auth/config/waffle.py

This change updates the `third_party_auth.always_associate_user_by_email` waffle switch's definition because Koa uses `edx-toggles=1.1.1`, instead of `2.0.0>edx-toggles>=1.2.0`.
* Jira Tickets: SE-3816, BB-3518
* Follow the testing instructions on https://github.com/edx/edx-platform/pull/25935
As soon as possible

Updates tpa email association waffle switch to support edx-toggles=1.1.1

---

cms/djangoapps/contentstore/tests/test_course_create_rerun.py
cms/djangoapps/contentstore/tests/test_libraries.py
cms/djangoapps/contentstore/views/course.py
cms/djangoapps/contentstore/views/library.py
cms/envs/common.py
common/djangoapps/student/auth.py

The condition added to ensure that if the feature is enabled
user will not be able to create the course outside of the organisation
in which they belong.
**JIRA tickets**: [BB-3622](https://tasks.opencraft.com/browse/BB-3622) 
~~**Discussions**: Link to any public dicussions about this PR or the design/architecture. Otherwise omit this.~~
~~**Sandbox URL**: TBD - sandbox is being provisioned.~~
~~**Merge deadline**: "None" if there's no rush, "ASAP" if it's critical, or provide a specific date if there is one.~~
1. Get the devstack up and running
2. Pull this branch in edx-platform
3. Drop in the studio shell `make dev.shell.studio`
4. vim /edx/etc/studio.yml
5. In the `FEATURES` dictionary add …

[BB-3622] Restrict user create course

---

cms/djangoapps/contentstore/views/preview.py
cms/templates/studio_xblock_wrapper.html

_The original PR for this bugfix is https://github.com/open-craft/edx-platform/pull/323_
We're fixing an error that appears when you click the "edit access" button on an XBlock in the library page. 
Libraries in the "Add library" page shouldn't have the accessibility config icon. Access settings for libraries are changed at the top, on Settings > User Access.
When clicking the access-button (the cog) on a Library, an error appears.
This is know to happen on koa.master and open-release/juniper.3.
More on "Other information"
([Sandbox link](https://manage.opencraft.com/instance/25060/))
1. Create a new library
2. Add a component
3. Click the cogwheel button
4. You should see this error (group configurations don't apply to Libraries because they're a particular type of XBlock that can be …

[BB-3710] Stop rendering Visibility button on libraries (juniper.3)

---

cms/djangoapps/contentstore/views/preview.py

We're fixing an error that appears when you click the "edit access" button on an XBlock in the library page. 
Libraries in the "Add library" page shouldn't have the accessibility config icon. Access settings for libraries are changed at the top, on Settings > User Access.
When clicking the access-button (the cog) on a Library, an error appears.
This is know to happen on koa.master and open-release/juniper.3.
More on "Other information"
([Sandbox link](https://manage.opencraft.com/instance/25060/))
1. Create a new library
2. Add a component
3. Click the cogwheel button
4. You should see this error (group configurations don't apply to Libraries because they're a particular type of XBlock that can be reused throughout its course org)
5. **This fix removes the access button**. You can pull …

[BB-3710] Stop rendering Visibility and Move buttons on libraries (koa.2a)

---

cms/djangoapps/contentstore/views/preview.py

This reverts https://github.com/open-craft/edx-platform/pull/323 since upstream found an issue and [reverted it](https://github.com/edx/edx-platform/pull/26885#issuecomment-805022096).

[BB-3710] Revert: Stop rendering Visibility and Move buttons on libraries (koa.2a)

---

cms/djangoapps/contentstore/views/preview.py

Backport the fix for Stop rendering Visibility and Move buttons on libraries.
(cherry picked from commit 2379f1ca26c127f5fccfd770419273ce35f32136)

[BB-3710] [Backport] fix: Stop rendering Visibility and Move buttons on libraries (juniper.3)

---

cms/djangoapps/contentstore/views/preview.py

Backport the fix for Stop rendering Visibility and Move buttons on libraries.
(cherry picked from commit 2379f1ca26c127f5fccfd770419273ce35f32136)

[BB-3710] [Backport] fix: Stop rendering Visibility and Move buttons on libraries (Koa.2a)

---

requirements/edx/base.txt

This upgrades the xblock to 0.9 which fixes a bug related to JS function intialization : https://github.com/edx/staff_graded-xblock/pull/18
**JIRA tickets**: [FAL-1730](https://tasks.opencraft.com/browse/FAL-1730)
**Reviewers**

Upgrade staff-graded-xblock to 0.9

---

lms/envs/common.py
lms/templates/courseware/course_about.html

Adds toggle REDIRECT_UNAUTHENTICATED_USER_TO_LOGIN_ON_ENROLL
for enrollment behaviour for unauthenticated user.
If true, the user will be redirected to 'signin_user' route.
**JIRA Tickets** [BB-3954](https://tasks.opencraft.com/browse/BB-3954)
**Testing Instructions**
1. Checkout to this branch in your `juniper` devstack.
2. Attach to `lms` shell using `make lms-shell`.
3. Edit `/edx/etc/lms.yml` and add `REDIRECT_UNAUTHENTICATED_USER_TO_LOGIN_ON_ENROLL: true`
4. Restart lms using `make lms-restart`
5. Visit about page for Demo course on LMS
6. Make sure you are unauthenticated.
7. Click 'Enroll Now'
8. Verify that the page redirects to login page.
9. Login with audit user.
10. Verify that the user is redirected to Demo course about page.

BB-3954 Add toggle for enrollment behavior

---

lms/djangoapps/courseware/tabs.py

In this PR I removed static tabs priority, to [make this reordering function](https://github.com/open-craft/edx-platform/blob/esme-oxford-release/koa.2a/lms/djangoapps/courseware/tabs.py#L383) works correctly
While we had default `priority` attribute set for `ProgressTab` `CoursewareTab`
[get_course_tab_list()](https://github.com/open-craft/edx-platform/blob/esme-oxford-release/koa.2a/lms/djangoapps/courseware/tabs.py#L383) returned incorrect order.
Issue is starting from this line where we get all dynamic tabs:
`course_tab_list += _get_dynamic_tabs(course, user)` we are getting correct order. 
For example:
`[[10, 'Course'], [inf, 'New Page'], [inf, 'Test'], [inf, 'Discussion'], [inf, 'Wiki'], [40, 'Progress'], [inf, 'Instructor']]`
But after doing sorting next time(for correctly sort …

[SE-4305] Reordering tabs not working in Koa

---

lms/djangoapps/grades/models.py

This PR is trying to address a hard-to-reproduce VisibleBlocks per-user caching issue in which case bulk create results an IntegrityError, though it shouldn't
**Discussions**: [Forum post](https://discuss.openedx.org/t/need-information-about-persistent-grades/1412/7?u=gabor)
N/A
1. TBD
1. The issue is really hard to reproduce as it is based on a possible race condition
**Reviewers**

[SE-4101] address VisibleBlocks caching race condition

---

lms/djangoapps/courseware/tabs.py

In this PR I removed static tabs priority, to [make this reordering function](https://github.com/open-craft/edx-platform/blob/esme-oxford-release/koa.2a/lms/djangoapps/courseware/tabs.py#L383) works correctly
While we had default `priority` attribute set for `ProgressTab` `CoursewareTab`
[get_course_tab_list()](https://github.com/open-craft/edx-platform/blob/esme-oxford-release/koa.2a/lms/djangoapps/courseware/tabs.py#L383) returned incorrect order.
Issue is starting from this line where we get all dynamic tabs:
`course_tab_list += _get_dynamic_tabs(course, user)` we are getting correct order. 
For example:
`[[10, 'Course'], [inf, 'New Page'], [inf, 'Test'], [inf, 'Discussion'], [inf, 'Wiki'], [40, 'Progress'], [inf, 'Instructor']]`
But after doing sorting next time(for correctly sort …

Reordering tabs not working

---

requirements/edx/base.in
requirements/edx/base.txt
requirements/edx/development.txt
requirements/edx/github.in
requirements/edx/testing.txt

Currently installing Ironwood is broken, because the py2neo authors decided to remove the installable packages of the versions we were using.
```
Could not find a version that satisfies the requirement py2neo==3.1.2 (from -r /edx/app/edxapp/edx-platform/requirements/edx/base.txt (line 188)) (from versions: 4.0.0, 4.1.0, 4.1.1, 4.1.2, 4.1.3, 4.2.0, 4.3.0, 2020.0.0, 2020.1.0, 2020.1.1, 2021.0.0, 2021.0.1)
```
For details see:
https://discuss.openedx.org/t/py2neo-installation-failure-affects-at-least-ironwood-and-juniper/4762
[Mattermost](https://chat.opencraft.com/opencraft/channels/hosting-subteam/c3fya6id5igh9mpnmcr5dauakh) thread for details.
https://groups.google.com/g/open-edx-btr-notifications/c/c_SB98vhwDs/m/nzVV8SDRCQAJ
This has been patched in upstream Juniper: …

[SE-4300] Use github version of py2neo instead of PyPI

---

common/lib/xmodule/xmodule/js/spec/video/completion_spec.js
common/lib/xmodule/xmodule/js/spec/video/video_events_plugin_spec.js
common/lib/xmodule/xmodule/js/src/video/09_completion.js
common/lib/xmodule/xmodule/js/src/video/09_events_plugin.js

This pull request is about reverting #256 and #266 since we won't merge those into `upstream` (https://github.com/edx/edx-platform/pull/25038).
**Jira ticket**: [SE-3248](https://tasks.opencraft.com/browse/SE-3248)
**Testing instructions**: Manually check that the changes have been reverted by doing a diff.
**Reviewers**: @nizarmah

[SE-3248] Revert `progress_video` event changes

---

lms/djangoapps/courseware/context_processor.py

We noted that when using the Site Configuration language customizations, course ending dates on the dashboard were not translated. These bypass the [DarkLangMiddleware where we have the other customizations which select language from the SiteConfiguration](https://github.com/open-craft/edx-platform/blob/6ff823abf27a8fb733532403456a7448bac780d8/openedx/core/djangoapps/dark_lang/middleware.py#L84).
**JIRA tickets**: Implements BB-3977
**Discussions**:  Issue discussed primarily on slack with client.
1. Add a [DarkLangConfig in the devstack](http://localhost:18000/admin/dark_lang/darklangconfig/) for a language other than English which has dates sufficiently different from English ("ar", "ja", or "zh_CN" are good …

Query Site Configuration Language When Rendering Datetimes

---

cms/djangoapps/contentstore/tests/test_course_create_rerun.py
cms/djangoapps/contentstore/tests/test_libraries.py
cms/djangoapps/contentstore/views/course.py
cms/djangoapps/contentstore/views/library.py
cms/envs/common.py
common/djangoapps/student/auth.py

Port https://github.com/open-craft/edx-platform/pull/319

[BB-3622] Restrict user create course (#319)

---

lms/djangoapps/certificates/views/webview.py
lms/envs/common.py

This is a backport PR of edx#25777

Cherry Pick of BB-3306 (Koa)

---

lms/djangoapps/grades/course_data.py
lms/djangoapps/grades/course_grade.py
lms/djangoapps/instructor_task/tests/test_tasks_helper.py

When getting a subsection grade for a user, instead of failing
if the user can't access that subsection,
fallback to the collected structure.
Related issues:
* [BB-4005](https://tasks.opencraft.com/browse/BB-4005)

fix: Produce grade report when subsections have future start dates [BB-4005]

---

lms/templates/instructor/instructor_dashboard_2/certificates.html

This reverts commit 8910ccfb7521e3a1fde00da1c4b286ee9fd96fcb ( https://github.com/open-craft/edx-platform/pull/219 ).
Our clients are no longer using this feature, and edX won't accept this
upstream as-is currently.  See https://github.com/edx/edx-platform/pull/23735 for more information.
Reverting to reduce code drift from upstream.
- verify that this cleanly reverts https://github.com/open-craft/edx-platform/pull/219
**Reviewers**:

FAL-867 Revert "Unhide student-generated certificates toggle"

---

openedx/core/djangoapps/user_authn/views/login.py

This is a typo and also a bug, the function was not called but referenced as a variable. Hence it was evaluating `True`.
**JIRA tickets**: [BB-4299](https://tasks.opencraft.com/browse/BB-4299)
~~**Discussions**: Link to any public dicussions about this PR or the design/architecture. Otherwise omit this.~~
~~**Dependencies**: None~~
~~**Screenshots**: Always include screenshots if there is any change to the UI.~~
~~**Sandbox URL**: TBD - sandbox is being provisioned.~~
~~**Merge deadline**: "None" if there's no rush, "ASAP" if it's critical, or provide a specific date if there is one.~~
1. Get the koa devstack working
2.
```diff
diff --git a/lms/envs/devstack.py b/lms/envs/devstack.py
index 8dc01e8024..f6c7fd5ef9 100644
--- a/lms/envs/devstack.py
+++ …
```

fix:Fix function call to check MFE

---

cms/static/js/factories/settings.js

Backport of https://github.com/edx/edx-platform/pull/27979 to `opencraft-release/koa.3`.
**JIRA tickets**:
- [BB-4385](https://tasks.opencraft.com/browse/BB-4385)
1. Using your local devstack, make the same action as shown on image from description and make sure that issue is resolved.
**Reviewers**

[BB-4385] Prevent course details AJAX request from getting into browser history (backport)

---

openedx/core/djangoapps/dark_lang/middleware.py
openedx/core/djangoapps/dark_lang/tests.py

Cherry-picked from: https://github.com/edx/edx-platform/pull/27696. Description and test instructions are pretty the same as in original PR.

[BB-2862] "LANGUAGE_CODE" site configuration option (backport)

---

common/lib/capa/capa/safe_exec/safe_exec.py
common/lib/capa/capa/safe_exec/tests/test_safe_exec.py
requirements/edx-sandbox/py35.in
requirements/edx-sandbox/py35.txt

Reverts open-craft/edx-platform#343
Upstream [pushed back on this change](https://github.com/edx/edx-platform/pull/27372#issuecomment-858506456), questioning how `matplotlib` could even be used in Python-Evaluated Input problems. We reached out to the client about this but got no answer, so reverting the change to prevent code drift in our release branches.
**Sandbox**
* LMS: https://pr365.sandbox.stage.opencraft.hosting/
* Studio: https://studio.pr365.sandbox.stage.opencraft.hosting/
**Author Notes & Concerns**
1. This shouldn't need an internal review, will merge when the sandbox provisions ok.

Revert "[FAL-1813] fix: codejail issue when using matplotlib"

---

cms/djangoapps/contentstore/config/waffle.py
cms/djangoapps/contentstore/permissions.py
cms/djangoapps/contentstore/views/item.py
cms/djangoapps/contentstore/views/tests/test_item.py
cms/static/js/spec/views/pages/course_outline_spec.js
cms/static/js/views/xblock_outline.js
cms/templates/js/course-outline.underscore

This PR and a check to show/hide the delete button on the course content in Studio. With these changes, the delete button is only visible to the admin user one with the `CourseInstructor`  role only and will not be visible to the  `CourseStaff`  role users.
Course Outline view for the user when it has *admin* access to the course
Course Outline view for the user when it has *staff* access to the course
JIRA Ticket: [SE-4482](https://tasks.opencraft.com/browse/SE-4482)
- Login with `staff@example.com`  on `https://studio.pr360.sandbox.opencraft.hosting/`. 
-  Go to the setting > Course team of the  *Demonstration Course* 
-  Add `verified@example.com` as the staff for the course
-  Login from the `verified@example.com` on the studio page
-  `verified@example.com` should not be able to see …

[SE-4482] Allow delete course content in Studio only for admin users

---

lms/static/js/student_account/views/AccessView.js

The password-reset page throws page not found error on refresh. This started happening in koa.
**JIRA tickets**: [BB-4386](https://tasks.opencraft.com/browse/BB-4386)
~~**Discussions**: Link to any public dicussions about this PR or the design/architecture. Otherwise omit this.~~
~~**Dependencies**: None~~
Juniper Behaviour
Koa Behaviour
~~**Merge deadline**: "None" if there's no rush, "ASAP" if it's critical, or provide a specific date if there is one.~~
1.  Use koa devstack
2.  Go to the sign-in page  click on need more help and then password-reset page
3. Hit refresh you will get a page not found error
4. Pull in the code, do a `make lms-static` and `make lms-restart`
5. Repeat the above …

fix: Passwored reset page throwing page not found error

---

lms/templates/wiki/history.html

The action buttons in wiki modal have href attribute
but does not have an event listener for click.
This PR changes the buttons to anchor tags so that they
work as expected when clicked.
- [BB-4360](https://tasks.opencraft.com/browse/BB-4360)
1.  Enroll in any Course
2. Go to Wiki
3. Create an article
4. Make 2-3 edits and save after each edit
5. Click on Changes
6. Select any revision and click "Merge selected with current"
8. Click "Create new merged version". Check that this does not trigger any action.
1. Checkout to this branch.
2. Go to Wiki
3. Create an article
4. Make 2-3 edits and save after each edit
5. Click on Changes
6. Select any revision and click "Merge selected with current"
8. Click "Create new merged version".
9. Verify that this triggers a merge request.
10. Wait for …

fix: change buttons in wiki modal to anchor tags

---

lms/djangoapps/certificates/services.py
lms/djangoapps/certificates/signals.py

The allowlisted certificates were getting invalidated upon visiting the Course Progress page by users.
This is a rough backport of the Lilac fix (edx#26356). In Lilac, this is gated by the `certificates_revamp.use_allowlist` Waffle flag. In post-Lilac branches, this is working out of the box (the flag has been removed in edx#27576).
**Note:** if you are using the Lilac release, you don't need these changes - you can get them by enabling the [certificates_revamp.use_allowlist](https://github.com/edx/edx-platform/blob/13d174fdda00e898c7af58551e63c70d69ba5c5a/lms/djangoapps/certificates/generation_handler.py#L34-L47) flag in [Django admin](http://localhost:18000/admin/waffle/flag/)
1. Add `FEATURES['CERTIFICATES_HTML_VIEW'] = True` to `{lms,cms}/envs/private.py`.
1. Add a "Verified" mode …

fix: prevent invalidation of allowlisted certificates [BB-4287]

---

cms/celery.py
cms/djangoapps/contentstore/tasks.py
cms/envs/production.py
cms/envs/test.py
common/djangoapps/entitlements/tasks.py
lms/celery.py
lms/djangoapps/bulk_email/tasks.py
lms/djangoapps/discussion/tasks.py
lms/djangoapps/email_marketing/tasks.py
lms/djangoapps/gating/tasks.py
lms/djangoapps/grades/management/commands/compute_grades.py
lms/djangoapps/grades/management/commands/tests/test_compute_grades.py
lms/djangoapps/grades/tasks.py
lms/djangoapps/instructor_task/tasks.py
lms/djangoapps/verify_student/tasks.py
lms/envs/common.py
lms/envs/production.py
lms/envs/test.py
openedx/core/djangoapps/coursegraph/tasks.py
openedx/core/djangoapps/credentials/tasks/v1/tasks.py
openedx/core/djangoapps/heartbeat/tasks.py
openedx/core/djangoapps/heartbeat/tests/test_heartbeat.py
openedx/core/djangoapps/programs/tasks.py
openedx/core/djangoapps/schedules/tasks.py
openedx/core/lib/celery/routers.py
requirements/edx/base.txt
requirements/edx/development.txt
requirements/edx/testing.txt

Cherry-picks the following PRs from upstream koa.master:
* https://github.com/edx/edx-platform/pull/27629
* https://github.com/edx/edx-platform/pull/27691
* https://github.com/edx/edx-platform/pull/28034
Sandbox (provisioning):
* LMS: https://pr367.sandbox.stage.opencraft.hosting/
* Studio: https://studio.pr367.sandbox.stage.opencraft.hosting/
Ensure that the sandbox provisions, and the appserver's extended celery checks work as expected.
**Author Notes & Concerns**
* At time of writing, https://github.com/edx/edx-platform/pull/28034 hasn't been merged to master or koa.master yet, but should be soon.
**Reviewer**

[FAL-2076] Cherry-pick celery fixes on Koa.3

---

cms/envs/common.py
cms/envs/production.py
lms/envs/common.py
lms/envs/production.py

This Pull Request adds `CELERYBEAT_SCHEDULER` to the edx-platform and sets it to its default value defined by Celery [documentation](https://docs.celeryproject.org/en/v4.4.7/userguide/configuration.html#beat-scheduler).
The configuration repository PR: https://github.com/open-craft/configuration/pull/170
Settings
```yaml
ADDL_INSTALLED_APPS:
- django_celery_beat
EDXAPP_ENABLE_CELERY_BEAT: true
SANDBOX_ENABLE_REDIS: true
EDXAPP_CELERY_BROKER_TRANSPORT: 'redis'
EDXAPP_CELERY_BROKER_HOSTNAME: '127.0.0.1:6379'
EDXAPP_CELERY_BROKER_USE_SSL: false
EDXAPP_CELERY_BROKER_VHOST: '/0'
EDXAPP_CELERY_USER: 'default'
EDXAPP_CELERY_PASSWORD: ''
EDXAPP_CELERYBEAT_SCHEDULER: django_celery_beat.schedulers:DatabaseScheduler
```
**Dependencies**:
https://github.com/open-craft/configuration/pull/170
**Sandbox …

[SE-4304] [SE-4495] feat: add celery beat configuration to Koa

---

lms/djangoapps/instructor_task/api.py
lms/djangoapps/instructor_task/models.py
lms/djangoapps/instructor_task/tasks_helper/enrollments.py
lms/djangoapps/instructor_task/tasks_helper/grades.py
lms/djangoapps/instructor_task/tasks_helper/utils.py
lms/djangoapps/instructor_task/tests/test_integration.py
lms/djangoapps/instructor_task/tests/test_tasks_helper.py

This PR is a cherry-pick of #27269 and allows to set a custom upload directory path and filename for the grade and calculated profile reports through their task_inputs.

feat: add custom task kwargs

---

common/static/common/js/discussion/utils.js

(cherry picked from commit 82939c3423756941261ab103d228e191aa31e81d)
This backports edx/edx-platform#28371 to our common Koa branch.
1. Check that the diff is matching the original PR.

fix: discussion xss fix [BB-4600]

---

requirements/edx/base.txt
requirements/edx/development.txt
requirements/edx/testing.txt

This PR updates the lti-consumer-xblock version to a [new branch](https://github.com/open-craft/xblock-lti-consumer/tree/opencraft-release/koa.3) in opencraft's fork of xblock-lti-consumer, that contains the backported fix from [edx/xblock-lti-consumer#150](https://github.com/edx/xblock-lti-consumer/pull/150).

[SE-4235] Update lti-consumer-xblock to new commit

---

package-lock.json
package.json

This PR fixes duplicate Arabic month issue reported by NELP. The issue is due to our dependency on an old version of Moment JS. Relevant issues can be found on Moment JS [Github Issues](https://github.com/moment/moment/issues/4270).
https://tasks.opencraft.com/browse/BB-4649
Before this PR -
After this PR -
1. Checkout this PR on your local devstack
2. Change language to `ar` from `/update_lang` in the LMS
3. Check course start dates on the course listing page are correct.
None
**Reviewer**

[BB-4649] Fix duplicate Arabic month in course start date

---

lms/envs/common.py
lms/templates/courseware/course_about.html

This is a backport PR from https://github.com/edx/edx-platform/pull/27197

[BB-3954] Backport: Add toggle to redirect user to the login page on unauthenticated enrollement 

---

cms/__init__.py
lms/__init__.py

**Description**
This pulls in a [django patch](https://github.com/django/django/pull/14766) which significantly reduces migration times for our instances hosted on Ocim.
Migrations take around 15 minutes with this patch applied.
Without the patch, they can take more than an hour, depending on the number of MySQL users in the database. We've even had Ocim hit the 2 hour timeout while running migrations in some cases.
See https://tasks.opencraft.com/browse/FAL-2248 for more info.
1. Verify that [the sandbox](https://manage.opencraft.com/instance/29780/) was provisioned successfully.
2. Check the logs on [the appserver](https://manage.opencraft.com/instance/29780/edx-appserver/20394/) to verify that migrations took around 15 minutes and compare that time to some other …

FAL-2248: Monkey-patch django db introspection to avoid performance issues

---

cms/envs/production.py
lms/envs/production.py
requirements/constraints.txt
requirements/edx/base.txt
requirements/edx/development.txt
requirements/edx/testing.txt

Backports https://github.com/edx/edx-platform/pull/28020 to our koa.3 release branch.
Note that this code drift can be dropped once the [celery constraint is dropped](https://github.com/edx/edx-platform/blob/8058074c616d2efab29026f0fd1070459ff719ac/requirements/constraints.txt#L15-L16) and celery is updated to `>=5.2.0`, because it will pull in our upstream kombu changes which were released with [kombu v5.2.0rc1](https://github.com/celery/kombu/releases/tag/v5.2.0rc1).
Note that here, I use the tag [v4.6.11.1](https://github.com/open-craft/kombu/tree/v4.6.11.1) instead of the branch name; will update the upstream PR to use this too.
**Jira ticket**
[FAL-2030](https://tasks.opencraft.com/browse/FAL-2030)
**Sandbox**
Sandbox is provisioning:
* LMS: …

[FAL-2030] Updates kombu package to support multi-tenant redis authentication

---

requirements/edx/base.txt
requirements/edx/development.txt
requirements/edx/testing.txt

The previous lti-consumer-xblock commit hash was pointing to a code drift branch which was backporting https://github.com/edx/xblock-lti-consumer/pull/150 to tag `2.4.0`
Unfortunately, `config_id` duplicate errors started showing for one of the clients. Accordingly, we had to update the xblock to the latest version which inculded that fix and still supported koa (`2.10.1`).
However, https://github.com/edx/xblock-lti-consumer/pull/150 was not merged until tag `3.0.3`. Thefore, we created a custom tag, `2.10.1-opencraft` which includes the backported change on top of tag `2.10.1`
* **Jira Ticket**: SE-4851
* **Sandbox**:
* LMS: https://pr400.sandbox.stage.opencraft.hosting/
* Studio: https://studio.pr400.sandbox.stage.opencraft.hosting/
* [Compare `2.4.0-opencraft` against …

fix: update lti-consumer-xblock to 2.10.1

---

cms/envs/production.py
lms/envs/production.py

Cherry-pick of https://github.com/edx/edx-platform/pull/28849
The release of Redis 6 introduced the ability to share this service among multiple accounts, securing the access to specific keys using a username/password and ACLs. Celery uses kombu to provide Redis brokering for the message queues, but kombu was missing a couple of key enhancements to support multi-tenant redis.
This PR allows to configure the broker transport options to enjoy the benefits of the above-mentioned updates.
OpenCraft wants to use multi-tenant Redis for their shared hosting service, so we can stop maintaining RabbitMQ.
None
The initial PR that partially contained these changes: https://github.com/edx/edx-platform/pull/28020

feat: adds CELERY_BROKER_TRANSPORT_OPTIONS

---

openedx/core/djangoapps/user_authn/views/registration_form.py
openedx/core/djangoapps/user_authn/views/tests/test_register.py

This PR cherry-picks https://github.com/edx/edx-platform/pull/26633
1. Navigate [here](https://esme-staging.opencraft.hosting/register)
2. Validate that the text " I hereby confirm receiving updates on new courses, content and new learning initiatives " follows "Password" field.

[SE-4888] Cherry-pick Fix use a registration field order when using a registration extension

---

common/lib/xmodule/xmodule/course_module.py
lms/djangoapps/courseware/tests/test_views.py
lms/djangoapps/courseware/views/index.py
lms/djangoapps/courseware/views/views.py
lms/templates/main.html
lms/templates/main_django.html

Cherry-pick of https://github.com/edx/edx-platform/pull/28411
Imlements OEP-15 by adding two fields to the course settings:
- Course-wide Custom JS
- Course-wide Custom CSS
The resources defined in these fields will be rendered in all course pages.
Rebase b6cb629849..0578e1c4c6 onto b6cb629849:
- Add course-wide resources to API for MFE use
- Revert "Add course-wide resources to API for MFE use" reverts commit 53648dcf0afe3cd171c9dc2eb5e56b871b2bcfb2
Signed-off-by: Gabor Boros <gabor.brs@gmail.com>
1. go to [this page](https://esme-readspeaker.opencraft.hosting/courses/course-v1:edX+DemoX+Demo_Course/courseware/d8a6192ade314473a78242dfeedfbf5b/edx_introduction/?activate_block_id=block-v1%3AedX%2BDemoX%2BDemo_Course%2Btype%40sequential%2Bblock%40edx_introduction)
2. Validate the "listen …

[SE-4650] feat: Add course-wide custom scripts

---

cms/envs/common.py
common/djangoapps/student/tests/test_enrollment.py
common/djangoapps/student/views/dashboard.py
common/djangoapps/student/views/management.py
lms/envs/common.py
lms/templates/dashboard.html
lms/templates/dashboard/_dashboard_course_listing.html
lms/templates/dashboard/_dashboard_entitlement_actions.html

This PR Implements a feature flag `DISABLE_UNENROLLMENT` that is used to disable students un-enrollment for all courses. The `Unenrollment` option should be disabled when this feature is set to `True`
[BB-4951](https://tasks.opencraft.com/browse/BB-4951)
- Check out to this branch `tinumide/lilac_disable_unenrollment` in the edx-plaftorm repository on a lilac devstack
- In the lms.yml file add `DISABLE_UNENROLLMENT: true` to Features
- Go to the Lms dashboard at `http://localhost:18000/dashboard` and click on the settings gear of a course
- Confirm that there is no option to unenroll

Implement feature flag to disable students un-enrollment [BB-4951]

---

common/djangoapps/util/file.py
common/djangoapps/util/tests/test_file.py
lms/envs/common.py

This is the backport of https://github.com/edx/edx-platform/pull/27028.
---
This pull requests backport a feature to include CCX course IDs in the generated course filenames used for downloading reports, etc.
The suffix appended to the generated filename prefix is following the  `<separator>_ccx_<ccx id>` pattern, to ensure unique filename generation per ccx - previously all CCX courses were downloaded with the same name.
1. Navigate to https://pr29101.sandbox.opencraft.hosting
2. Login as staff
3. Navigate to https://pr29101.sandbox.opencraft.hosting/courses/ccx-v1:edX+DemoX+Demo_Course+ccx@1/instructor#view-data_download
4. Click "Download profile information as a CSV" button …

[SE-4631] feat: add CCX ID to generated filename prefixes (#27028)

---

common/djangoapps/util/file.py
common/djangoapps/util/tests/test_file.py
lms/envs/common.py

This is the backport of https://github.com/edx/edx-platform/pull/27028.
---
This pull requests backport a feature to include CCX course IDs in the generated course filenames used for downloading reports, etc.
The suffix appended to the generated filename prefix is following the  `<separator>_ccx_<ccx id>` pattern, to ensure unique filename generation per ccx - previously all CCX courses were downloaded with the same name.
1. Navigate to https://pr29101.sandbox.opencraft.hosting
2. Login as staff
3. Navigate to https://pr29101.sandbox.opencraft.hosting/courses/ccx-v1:edX+DemoX+Demo_Course+ccx@1/instructor#view-data_download
4. Click "Download profile information as a CSV" button …

[SE-4631] add CCX ID to generated filename prefixes (#27028)

---

lms/envs/common.py
lms/static/js/spec/student_account/register_spec.js
lms/static/js/student_account/views/RegisterView.js
openedx/core/djangoapps/user_api/helpers.py
openedx/core/djangoapps/user_api/tests/test_helpers.py
openedx/core/djangoapps/user_authn/views/registration_form.py
openedx/core/djangoapps/user_authn/views/tests/test_login.py
openedx/core/djangoapps/user_authn/views/tests/test_register.py
openedx/core/djangoapps/user_authn/views/tests/test_reset_password.py

This PR cherry-picks registration form improvements/bug fixes.
1. Defines optional extra fields that are not hidden under the toggle on the registration page
2. Fix use a registration field order when using a registration extension form
Cherry picked from commit 230795fb07dd32dd8f146a392285bf7bd23db978 and 6f0255bc6030adb977dce300c1c59db439424ff6
None
N/A

[SE-4891] Cherry pick: feat: add `optional-exposed` extra field type to registration form

---

lms/envs/common.py
openedx/core/djangoapps/user_authn/middleware.py
openedx/core/djangoapps/user_authn/tests/test_middlewares.py

This PR implements new middleware that redirects all unathenticated users to login page. It enables admins to enable the middleware through settings for LMS to prevent unathenticated users from seeing any content.
[BB-5090](https://tasks.opencraft.com/browse/BB-5090)
* Run `make lms-up` in the devstack
* Visit `http://localhost:18000/courses/` (logout before that, if you're logged in) - you will be able to see the available courses
* Run `make lms-shell` in the devstack, open `/edx/etc/lms.yml` and under 'FEATURES' add `ENABLE_REDIRECT_UNATHENTICATED_USERS_TO_LOGIN: true`
* Exit the lms shell and run `make lms-restart-devserver`
* Now if you visit `http://localhost:18000/courses/`, you'll be redirected to login page
* If you log in, you should get redirected to the page you've tried to …

feat: implement login redirect middleware [BB-5090]

---

cms/djangoapps/contentstore/views/item.py
cms/djangoapps/contentstore/views/tests/test_item.py

Fix a couple of minor issues with [SE-4482](https://github.com/open-craft/edx-platform/pull/360). Specifically the delete icon would reappear when the visibility of a section was changed.
JIRA Ticket: [SE-4482](https://tasks.opencraft.com/browse/SE-4482)
- Login on `https://studio.pr440.sandbox.stage.opencraft.hosting/`.
- Enable PREVENT_STAFF_STRUCTURE_DELETION waffle flag from `https://studio.pr440.sandbox.stage.opencraft.hosting/admin`
-  Go to the setting > Course team of the  *Demonstration Course* 
-  Add `verified@example.com` as the staff for the course
-  Login from the `verified@example.com` on the studio page
-  `verified@example.com` should not be able to see the delete button on the course outline page.
- Change the visibility of a section like …

Fix: Allow delete course content in Studio only for admin users

---

cms/djangoapps/contentstore/views/item.py
cms/djangoapps/contentstore/views/tests/test_import_export.py
cms/envs/common.py
cms/envs/production.py
cms/static/js/views/modals/course_outline_modals.js
cms/static/js/views/pages/course_outline.js
common/lib/xmodule/xmodule/assets/library_content/public/js/library_content_reset.js
common/lib/xmodule/xmodule/capa_module.py
common/lib/xmodule/xmodule/library_content_module.py
common/lib/xmodule/xmodule/modulestore/xml.py
common/lib/xmodule/xmodule/modulestore/xml_importer.py
common/lib/xmodule/xmodule/tests/test_capa_module.py
common/lib/xmodule/xmodule/tests/test_library_content.py
common/lib/xmodule/xmodule/xml_module.py
common/static/common/js/discussion/views/discussion_inline_view.js
common/static/common/js/spec/discussion/view/discussion_inline_view_spec.js
common/static/sass/edx-pattern-library-shims/_breadcrumbs.scss
lms/djangoapps/instructor_analytics/basic.py
lms/envs/common.py
lms/static/js/views/fields.js
lms/static/sass/course/courseware/_courseware.scss
lms/templates/courseware/courseware.html
lms/templates/preview_menu.html
lms/templates/vert_module.html
openedx/core/lib/xblock_utils/__init__.py
openedx/tests/completion_integration/test_services.py

This cherry-picks the following PRs:
- https://github.com/edx/edx-platform/pull/26860
- https://github.com/edx/edx-platform/pull/25950
- https://github.com/edx/edx-platform/pull/27022
- https://github.com/edx/edx-platform/pull/27799
- https://github.com/edx/edx-platform/pull/28028
- https://github.com/edx/edx-platform/pull/28207
- https://github.com/edx/edx-platform/pull/23171
- https://github.com/edx/edx-platform/pull/27466 - not clean
- https://github.com/edx/edx-platform/pull/28557
- https://github.com/edx/edx-platform/pull/28268 - not clean
- https://github.com/edx/edx-platform/pull/28624
- https://github.com/edx/edx-platform/pull/29106

chore: port echo drift to lilac [BB-4704]

---

common/lib/xmodule/xmodule/js/src/sequence/display.js
common/lib/xmodule/xmodule/seq_module.py
lms/templates/courseware/courseware.html
lms/templates/seq_module.html

**Description:** 
This PR implements the changes needed to show course progress bar on the courseware page. There are two progress bars that will be displayed: One at the course level and the other one at section/chapter level.
**JIRA:** [SE-4473](https://tasks.opencraft.com/browse/SE-4473)
**Testing instructions:**
1. Setup your devstack with this branch.
2. Set the feature flag `SHOW_PROGRESS_BAR` to true under `FEATURES` in lms.yml and studio.yml.
3. Add the `COMPLETION_AGGREGATOR_URL` setting in lms.yml as shown below:
```
COMPLETION_AGGREGATOR_URL: /completion-aggregator/progress_bar
```
4. Ensure completion tracking is enabled.
5. Pip install completion-aggregator django app containing https://github.com/open-craft/openedx-completion-aggregator/pull/89.
6. Start new course in LMS …

[SE-4473] Implement progress bar

---

cms/djangoapps/contentstore/views/course.py
cms/static/cms/js/spec/main.js
cms/static/js/utils/date_utils.js

Currently in Studio, the coures date and time inputs in the "Schedule & Details" section are only in UTC.
This PR changes this to the user's prefered timezone as per the user's account settings.
- Which edX user roles will this change impact? "Course Author"
[BB-5271](https://tasks.opencraft.com/browse/BB-5271)
1. Login to LMS
2. Click on arrow beside username in upper-right corner
3. Select Account from drop-down menu
4. Set the Time Zone as prefered
5. Go to Studio and open a course
6. Go to Settings > Schedule & Details
7. Under Course Schedule, check Course date and times.
8. The times should be in the prefered timezone
9. Check the time is correcly offset from UTC time

[BB-5271] feat: Change studio schedule datetime inputs to user timezone

---

openedx/core/djangoapps/user_api/accounts/permissions.py
openedx/core/djangoapps/user_api/accounts/tests/test_views.py
openedx/core/djangoapps/user_api/accounts/views.py
openedx/core/djangoapps/user_authn/views/logout.py
openedx/core/djangoapps/user_authn/views/tests/test_logout.py

This PR applies the security patches required backported to Lilac. Cherry-picked from https://github.com/overhangio/edx-platform/commit/78da3d86b79e808462b88f219efb90bf8253a5d1
and https://github.com/overhangio/edx-platform/commit/b63c01fb38a60f4581bdecbc528fa64cc3d3ef0d
**Jira Tickets:** [SE-5163](https://tasks.opencraft.com/browse/SE-5163)
- Verify that all the required changes from the two commits above are included.
**Reviewers:**

[SE-5163] Apply security patches for xss and email search from logout page

---

lms/templates/main.html

Prevent any unauthenticated users from being able to view LMS content, by redirecting them to the login page.
Implemented through changes to the theme, so that only the requests that would return a page with some content would get affected by this change. There has been an attempt at implementing it through a middleware (see BB-5090), however, it was interfering with admin panel, API endpoints and other urls.
[BB-5090](https://tasks.opencraft.com/browse/BB-5090)
[BB-5351](https://tasks.opencraft.com/browse/BB-5351)

feat: redirect unauthenticated users to login page [BB-5090] [BB-5351]

---

common/lib/xmodule/xmodule/assets/library_content/public/js/library_content_reset.js
common/lib/xmodule/xmodule/library_content_module.py
common/lib/xmodule/xmodule/tests/test_library_content.py

This backports [edx#29728](https://github.com/openedx/edx-platform/pull/29728) to the echo branch.

backport: reset a Randomized Content Block via AJAX

---

lms/djangoapps/instructor_task/tasks_helper/grades.py

Bugfix for the grade report task not uploading to the correct parent directory.
https://tasks.opencraft.com/browse/SE-5281
None

[SE-5281] Fixes grade report task parent dir not being used.

---

cms/djangoapps/contentstore/views/course.py
cms/envs/common.py
cms/static/js/utils/date_utils.js
cms/templates/settings.html

Adds the ability to configure Schedule & Details settings page with the ability to show `dd/mm/yyyy` format. Default setting maintains existing behavior and doesn't introduce anything new.
Why:
Some areas of the world operate with the day-first: `dd/mm/yyyy` rather than `mm/dd/yyyy`.
**JIRA tickets**: [BB-5329](https://tasks.opencraft.com/browse/BB-5429)
~~**Discussions**: Link to any public dicussions about this PR or the design/architecture. Otherwise omit this.~~
~~**Dependencies**: None~~
~~**Sandbox URL**: TBD - sandbox is being provisioned.~~
* Initialize lilac devstack to use branch
* Look at the studio --> course(Demo Course) --> settings --> Schedule and Details
* Go under the Course Schedule section and you will see the date format is …

[BB-5429] Added date configuration to Schedule & Details settings page

---

lms/static/certificates/sass/_components.scss

This reverts "Remove CSS that hides the signatures on custom certificates"
1. Checkout this branch
2. Install the ASU-YTP theme
3. Setup the certificate
4. Check the [certificate](http://localhost:18000/certificates/course/course-v1:edX+DemoX+Demo_Course?preview=verified), and see the signature is shown since theme is overwriting this

revert: Remove CSS that hides the signatures on custom certificates

---

openedx/core/djangoapps/password_policy/forms.py
openedx/core/djangoapps/user_authn/views/login.py

This PR converts the password compliance warning message back to HTML. It was converted to string as part of additional security but that resulted in HTML attributes not being applied while displaying the warning message.
**Jira tickets:** [BB-6041](https://tasks.opencraft.com/browse/BB-6041)
**Screenshots**
Before fix:
After fix:
The fix is already deployed to Esme staging so it can be verified there. The minimum password length has been set to 20.
1. Register/login with password less than the minimum length requirement.
2. After login, verify that the warning message is shown correctly.
**Reviewers:**

[BB-6041] Convert compliance warning back to html

---

cms/envs/common.py
common/lib/xmodule/xmodule/tests/test_resource_templates.py
common/lib/xmodule/xmodule/x_module.py
lms/envs/common.py

This PR contains cherry-picked changes from https://github.com/openedx/edx-platform/pull/30108/files. Duplicating the description below.
At Opencraft, we have clients that want to be able to add custom HTML templates that show up while creating course components in Studio.
Currently, there's no way to achieve this besides forking `edx-platform` and adding the `yaml` files to `common/lib/xmodule/xmodule/templates/`
This PR allows operators to set a custom directory where templates can be additionally loaded from.
- Checks if `settings.CUSTOM_RESOURCE_TEMPLATES_DIRECTORY` exists.
- If so, load the `yaml` files with the same logic as in the `xmodule/templates` directory.
- Configuration PR: https://github.com/openedx/configuration/pull/6706
- Custom Client Branch: …

feat: add custom html templates for components [bb-5885]

---

lms/templates/courseware/courseware.html
lms/templates/seq_module.html

When the feature `SHOW_PROGRESS_BAR` is set to True and the `COMPLETION_AGGREGATOR_URL` setting is not setup, lms raises template error `Undefined`.
This PR handles such a case by checking for `COMPLETION_AGGREGATOR_URL` as well as `SHOW_PROGRESS_BAR` setting in templates.
JIRA: [BB-6140](https://tasks.opencraft.com/browse/BB-6140)
```logs
edx.devstack-lilac.master.lms     | 2022-04-22 11:59:58,669 ERROR 8567 [root] [user None] [ip None] signals.py:22 - Uncaught exception from None
edx.devstack-lilac.master.lms     | Traceback (most recent call last):
edx.devstack-lilac.master.lms     |   File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
edx.devstack-lilac.master.lms     |     response = get_response(request) …
```

fix: handle missing COMPLETION_AGGREGATOR_URL setting

---

cms/envs/production.py
lms/envs/production.py

Cherry pick of: https://github.com/openedx/edx-platform/pull/30244
Currently, the `CELERY_RESULT_BACKEND` is hard coded to use `django-cache`.
This PR allows to setup `CELERY_RESULT_BACKEND` via `ENV_TOKENS`.
To use django ORM as celery backend, one can set `CELERY_RESULT_BACKEND` to `django-db` as described in [docs](https://docs.celeryq.dev/en/stable/django/first-steps-with-django.html#django-celery-results-using-the-django-orm-cache-as-a-result-backend).

fix: [BB-6077] allow setting celery backend in yml

---

requirements/edx/base.txt

Opening any unit in Studio results in this error:
```python
Apr 29 13:01:09 edxapp-demoopencrafthosting-appserver-109 [service_variant=cms][django.request][env:sandbox] ERROR [edxapp-demoopencrafthosting-appserver-109  1725] [user 6] [ip 94.125.122.82] [log.py:222] - Inter
--
nal Server Error: /container/block-v1:edX+DemoX+Demo_Course+type@vertical+block@d91b9e5d8bc64d57a1332d06bf2f2193
Traceback (most recent call last):
File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
response = get_response(request)
File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
response = self.process_exception_by_middleware(e, request)
File …
```

[SE-5561] Fix setuptools version conflict

---

webpack.common.config.js

This adds a fix after #472, which backported https://github.com/openedx/edx-platform/pull/30335.

chore: backport TinyMCE upgrade to echo branch v2 [BB-6151]

---

cms/envs/production.py
lms/envs/production.py

Cherry pick of: https://github.com/openedx/edx-platform/pull/30244
Currently, the `CELERY_RESULT_BACKEND` is hard coded to use `django-cache`.
This PR allows to setup `CELERY_RESULT_BACKEND` via `ENV_TOKENS`.
To use django ORM as celery backend, one can set `CELERY_RESULT_BACKEND` to `django-db` as described in [docs](https://docs.celeryq.dev/en/stable/django/first-steps-with-django.html#django-celery-results-using-the-django-orm-cache-as-a-result-backend).

refactor: [BB-6077] allow setting celery backend in yml

---

requirements/constraints.txt
requirements/edx-sandbox/py38.txt
requirements/edx/base.txt
requirements/edx/development.txt
requirements/edx/doc.txt
requirements/edx/github.in
requirements/edx/pip-tools.txt
requirements/edx/testing.txt

**Description**
_Cherry pick of https://github.com/openedx/edx-platform/pull/29046_
**Dependencies**
Related to https://github.com/open-craft/configuration/pull/198, which cherry picks celery upgrade config to maple branch in opencraft.
**Related tickets**
- [BB-6123](https://tasks.opencraft.com/browse/BB-6123)
- [SE-4860](https://tasks.opencraft.com/browse/SE-4860)

[BB-6123] - Backport Celery upgrade from edx:#29046

---

common/djangoapps/student/models.py
common/djangoapps/student/tests/test_events.py
common/djangoapps/student/tests/test_models.py
common/lib/xmodule/xmodule/course_metadata_utils.py
common/lib/xmodule/xmodule/course_module.py
common/lib/xmodule/xmodule/tests/test_course_metadata_utils.py
common/lib/xmodule/xmodule/tests/test_course_module.py
lms/djangoapps/courseware/access.py
lms/djangoapps/courseware/tests/test_access.py
lms/envs/common.py
openedx/core/djangoapps/content/course_overviews/models.py
openedx/core/djangoapps/content/course_overviews/tests/test_course_overviews.py

Cherrypick of commit be34c0d from openedx/edx-platform#29538
This PR seeks to address the following scenario:
1. Non-registered user is enrolled in a course
2. Course enrollment ends
3. User registers after course enrollment has ended
4. User in enrolled to the course anyways
This PR introduces a feature flag "DISABLE_ALLOWED_ENROLLMENT_IF_ENROLLMENT_CLOSED" which when set to True, the newly registered user is not automatically enrolled to the course if the enrollment has ended.
Impacted user roles : Learner
1. Set the "DISABLE_ALLOWED_ENROLLMENT_IF_ENROLLMENT_CLOSED" flag to true
2. As a staff user, enroll an email-id to a course and set auto-enroll to true.
3. From the studio settings, set the course enrollment end date to a past date, so that the enrollment ends.
4. Register to the …

[BB-5195] feat: disable allowed enrollment if enrollment closed

---

lms/djangoapps/courseware/context_processor.py
lms/djangoapps/courseware/tests/test_context_processor.py

This cherry-picks https://github.com/openedx/edx-platform/pull/29180 to our common Maple branch.

fix: fix side-wide language for legacy UI [BB-6388]

---

lms/static/js/student_account/views/AccessView.js

This PR fixes the issue of django messages being read before redirecting to dashboard page, due to enterprise api being
called even if the feature is disabled. Before maple release, there used to be a waffle switch named `ENABLE_MULTIPLE_USER_ENTERPRISES_FEATURE` that was checked before calling the api. This was deprecated in [edx-platform#28057](https://github.com/openedx/edx-platform/pull/28057) but was not replaced by any other check for enterprise integration. And so after each login, the enterprise api would be called, which would return 404 but was fetching the django messages (which clears it) and so page banner messages wouldn't show up when the user was redirected to the dashboard page.
JIRA: [BB-6438](https://tasks.opencraft.com/browse/BB-6438)
1. Deploy this branch
2. Create a …

[BB-6438] Check if feature is enabled before calling enterprise api

---

cms/envs/common.py
common/djangoapps/student/models.py
common/djangoapps/student/tests/tests.py
lms/envs/common.py

This cherry-picks https://github.com/openedx/edx-platform/pull/30832 to the common Maple branch.
The conflicts were trivial - only in `lms/envs/common.py` and `cms/envs/common.py`, so I'll merge this once the CI passes, as I've already reviewed an upstream PR.

cherry-pick: feat: allow switching anonymous user ID hashing algorithm from shake to md5 [BB-6533]

---

common/djangoapps/student/models.py
common/djangoapps/student/tests/test_events.py
common/djangoapps/student/tests/test_models.py
common/lib/xmodule/xmodule/course_metadata_utils.py
common/lib/xmodule/xmodule/course_module.py
common/lib/xmodule/xmodule/tests/test_course_metadata_utils.py
common/lib/xmodule/xmodule/tests/test_course_module.py
lms/djangoapps/courseware/access.py
lms/djangoapps/courseware/tests/test_access.py
lms/envs/common.py
openedx/core/djangoapps/content/course_overviews/models.py
openedx/core/djangoapps/content/course_overviews/tests/test_course_overviews.py

This is a backport of https://github.com/openedx/edx-platform/pull/29538 to a Maple stage environment.
Merging as an almost clean cherry-pick (it only had conflicts in `common/djangoapps/student/tests/test_events.py` and `lms/envs/common.py`).

feat: disable allowed enrollment if enrollment closed [BB-5195]

---

lms/djangoapps/instructor/tests/test_api.py
lms/djangoapps/instructor/tests/test_tools.py
lms/djangoapps/instructor/views/tools.py

This cherry-picks https://github.com/openedx/edx-platform/pull/30999 to the common Nutmeg branch.
Merging as a clean cherry-pick.

fix[nutmeg]: regenerate the cache on due date extensions [BB-6658]

---

cms/djangoapps/contentstore/utils.py
cms/djangoapps/contentstore/views/component.py
common/lib/xmodule/xmodule/js/src/sequence/display.js

Makes `Previous` and `Next` button in studio consistent, i.e. 
- clicking on next button takes you to next chapter if there are any chapters left in current subsection else takes you to first chapter 
of next subsection
- clicking on previous button takes you to previous chapter if there are any chapters present before the current chapter in current subsection else takes you to the last chapter of the previous subsection.
To do that, this MR:
- Cherry picks https://github.com/openedx/edx-platform/pull/29701
- Cherry picks https://github.com/openedx/edx-platform/pull/31193
`Private ref`: [Jira: BB-6820](https://tasks.opencraft.com/browse/BB-6820)
- Test `next` and `previous` buttons in studio and lms legacy UI

Makes previous and next button in studio consistent

---

common/lib/xmodule/xmodule/js/src/sequence/display.js

Legacy UI: Previous button should use prev_url if it in first position. In studio UI, it should always use prev_url. To make this possible we checking length of contents which is always zero for studio and more than 0 for legacy UI.
Cherry picks https://github.com/openedx/edx-platform/pull/31193
`Private ref`: [Jira: BB-6820](https://tasks.opencraft.com/browse/BB-6820)
- Test `next` and `previous` buttons in lms preview UI

fix: preview mode navigation previous button (that uses legacy UI)

---

common/lib/xmodule/xmodule/js/spec/html/edit_spec.js
common/lib/xmodule/xmodule/js/src/html/edit.js

This backports https://github.com/openedx/edx-platform/pull/31212 to fix https://github.com/open-craft/edx-platform/pull/493 in Maple.
During the upgrade to TinyMCE v5, we changed the content format to `text`. However, it ignores changes in HTML tags. This reverts the format to `raw`.

fix(maple): retrieve raw content from TinyMCE editor

---

cms/djangoapps/contentstore/views/component.py
cms/djangoapps/contentstore/views/tests/test_item.py

This backports https://github.com/openedx/edx-platform/pull/31219 to Nutmeg.
I wanted to use https://github.com/openedx/edx-platform/pull/31221 but it has an incorrect commit message.

fix(nutmeg): studio submit handler

---

common/lib/xmodule/xmodule/js/spec/html/edit_spec.js
common/lib/xmodule/xmodule/js/src/html/edit.js

This backports https://github.com/openedx/edx-platform/pull/31212 to fix https://github.com/open-craft/edx-platform/pull/494 in Nutmeg.
During the upgrade to TinyMCE v5, we changed the content format to `text`. However, it ignores changes in HTML tags. This reverts the format to `raw`.

fix(nutmeg): retrieve raw content from TinyMCE editor

---

lms/djangoapps/certificates/generation_handler.py
lms/djangoapps/grades/course_grade_factory.py
lms/djangoapps/grades/tests/test_course_grade_factory.py
openedx/core/djangoapps/enrollments/serializers.py

This PR fixes the infinite loop that can be caused by trying to serialize enrollments inside the handler of any of the course grade signals. In other words, if the handler of one of the course grade signals tried to serialize an enrollment, the serializer would call `CourseGradeFactory().read(...)`, which inside would call the `_update` method, which would send another course grade signal, creating an infinite loop.
The fix is backporting two commits from the openedx/edx-platform#29792, which add a parameter to `CourseGradeFactory.read` and `CourseGradeFactory._update` that allows to prevent the signals from being sent, and modifies the `CourseEnrollmentSerializer` to pass the new argument in the function calls.

fix: ytp_api package in maple

---

requirements/edx/base.in
requirements/edx/base.txt
requirements/edx/development.txt
requirements/edx/github.in
requirements/edx/testing.txt

BREAKING CHANGE: disallowed HTML tags (e.g. <script>) will no longer be rendered in LMS and Studio.
This cherry-picks https://github.com/openedx/edx-platform/pull/31354 to the common Nutmeg branch.

feat!: update Drag and Drop v2 XBlock to prevent XSS vulnerabilities (Nutmeg backport)

---

requirements/edx/base.in
requirements/edx/base.txt
requirements/edx/development.txt
requirements/edx/github.in
requirements/edx/testing.txt

BREAKING CHANGE: disallowed HTML tags (e.g. <script>) will no longer be rendered in LMS and Studio.
This backports https://github.com/open-craft/edx-platform/pull/512 to the common Maple branch.

feat!: update Drag and Drop v2 XBlock to prevent XSS vulnerabilities (Maple backport)

---

lms/djangoapps/mobile_api/users/tests.py
openedx/core/djangoapps/dark_lang/middleware.py
openedx/core/djangoapps/dark_lang/tests.py
openedx/core/djangoapps/lang_pref/middleware.py
openedx/core/djangoapps/lang_pref/tests/test_middleware.py

This backports https://github.com/openedx/edx-platform/pull/31408 to the common Nutmeg branch.

fix: use language specified in SiteConfiguration [BB-6930]

---

common/djangoapps/student/tests/tests.py
common/djangoapps/student/toggles.py
common/djangoapps/student/views/management.py

This change adds a new waffle switch to redirect a student to courseware after enrolment instead of the dashboard.
cherrypick of: https://github.com/openedx/edx-platform/pull/31715

feat: Add toggle to allow redirecting to courseware after enrollment

---

common/lib/xmodule/xmodule/library_content_module.py
common/lib/xmodule/xmodule/tests/test_library_content.py
lms/djangoapps/course_blocks/transformers/library_content.py

This backports https://github.com/openedx/edx-platform/pull/31788 to Nutmeg.
Setting max_count to a negative value resulted in raising an unhandled ValueError. Currently, it selects all children of the LibraryContentBlock.

feat[nutmeg]: allow using all components of LibraryContentBlock [BB-7062]

---

cms/djangoapps/api/v1/serializers/course_runs.py
cms/djangoapps/api/v1/tests/test_views/test_course_runs.py
cms/djangoapps/api/v1/views/course_runs.py

This backports [openedx#31794](https://github.com/openedx/edx-platform/pull/31794) to Nutmeg.
Adds a new studio endpoint for the existing clone_course method, so that external applications can call it using the following API:
```
/api/v1/course_runs/clone/
```
And passing the source_course_id (of an existing course) and destination_course_id (of a non-existing course) in the request data, like below:
```
{
"source_course_id": "course-v1:edX+DemoX+Demo_Course",
"destination_course_id": "course-v1:new+TestX+Demo_Course_Clone",
}
```
See parent PR for testing instructions.

feat[nutmeg]: add new endpoint for cloning course [BB-7106]

---

lms/djangoapps/courseware/tabs.py
lms/djangoapps/discussion/urls.py

Reverts commit 6ffea760ce4a1c983f6328f5cbcf9d639721ba95
Link to other information about the change, such as Jira issues, GitHub issues, or Discourse discussions.
Be sure to check they are publicly readable, or if not, repeat the information here.
Please provide detailed step-by-step instructions for testing this change.
"None" if there's no rush, or provide a specific date or event (and reason) if there is one.
OpenCraft internal ticket : [BB-7147](https://tasks.opencraft.com/browse/BB-7147)

revert: revert hide discussion tab change

---

lms/djangoapps/discussion/toggles.py
lms/djangoapps/discussion/views.py

Allow any user that's enrolled in a course to view the discussion forum.
The changes have been deployed to https://es1.kgdocluster.opencraft.hosting/. Create a new account and enroll into any course. You should be able to view the new discussion experience.
- [Deployed config](https://gitlab.com/opencraft/devstacks/keith/grove-do/-/blob/main/instances/es1/config.yml)
- [Deployed requirements](https://gitlab.com/opencraft/devstacks/keith/grove-do/-/blob/main/instances/es1/requirements.txt)

feat: enable discussions for all users

---

cms/djangoapps/contentstore/tests/test_libraries.py
cms/djangoapps/contentstore/views/item.py
cms/djangoapps/contentstore/views/tests/test_item.py
common/lib/xmodule/xmodule/modulestore/split_mongo/split.py
common/lib/xmodule/xmodule/modulestore/store_utilities.py
common/lib/xmodule/xmodule/modulestore/tests/test_store_utilities.py

Backport of [https://github.com/openedx/edx-platform/pull/32058](https://github.com/openedx/edx-platform/pull/32058)

refactor: Duplicate and update primitives made available.

---

lms/djangoapps/instructor/tests/test_api.py
lms/djangoapps/instructor/views/api.py

This backports https://github.com/openedx/edx-platform/pull/32116 to the common Nutmeg branch.

fix(nutmeg): support files with a unicode signature in the Instructor Dashboard API

---

openedx/features/course_experience/__init__.py
openedx/features/course_experience/api/v1/tests/test_views.py
openedx/features/course_experience/utils.py

This backports https://github.com/openedx/edx-platform/pull/32148 to the common Nutmeg branch.

feat(nutmeg): add Waffle Flag to disable resetting self-paced deadlines by learners

---

openedx/features/course_experience/__init__.py

This fixes the backport from https://github.com/open-craft/edx-platform/pull/536. It will no longer be needed after Nutmeg.

fix: use old-style Course Waffle flag for `RELATIVE_DATES_DISABLE_RESET_FLAG`

---

cms/djangoapps/contentstore/rest_api/v0/tests/test_details_settings.py
cms/djangoapps/contentstore/rest_api/v0/urls.py
cms/djangoapps/contentstore/rest_api/v0/views/__init__.py
cms/djangoapps/contentstore/rest_api/v0/views/details_settings.py
cms/djangoapps/contentstore/views/course.py
common/djangoapps/util/json_request.py

This PR backports the changes made to the edx-platform as part of [BB-7296](https://tasks.opencraft.com/browse/BB-7296) onto opencraft's nutmeg branch.
See [parent PR](https://github.com/openedx/edx-platform/pull/32127) for details.

[BB-7296] Extend settings handler to be accessible via api

---

lms/djangoapps/instructor/tests/test_api.py
lms/djangoapps/instructor/views/api.py
lms/static/js/instructor_dashboard/membership.js

Cherry pick from https://github.com/openedx/edx-platform/pull/32436

fix: allow only enrolled users in course forum roles

---

common/djangoapps/student/auth.py
common/djangoapps/student/roles.py
common/djangoapps/student/tests/test_authz.py
common/djangoapps/student/tests/test_roles.py
lms/djangoapps/instructor/access.py
lms/static/js/fixtures/instructor_dashboard/membership.html
lms/templates/instructor/instructor_dashboard_2/membership.html

Backport of https://github.com/openedx/edx-platform/pull/32570.

feat: create Course Limited Staff role [BB-7503]

---

common/djangoapps/student/auth.py
common/djangoapps/student/roles.py
common/djangoapps/student/tests/test_authz.py
common/djangoapps/student/tests/test_roles.py
lms/djangoapps/instructor/access.py
lms/static/js/fixtures/instructor_dashboard/membership.html
lms/templates/instructor/instructor_dashboard_2/membership.html

Backport of https://github.com/openedx/edx-platform/pull/32570.
We cherry-picked this to Nutmeg in  https://github.com/open-craft/edx-platform/pull/546.

feat(palm): create Course Limited Staff role [BB-7503]

---

docs/swagger.yaml
lms/djangoapps/branding/__init__.py
lms/djangoapps/course_api/api.py
lms/djangoapps/course_api/forms.py
lms/djangoapps/course_api/tests/test_api.py
lms/djangoapps/course_api/tests/test_forms.py
lms/djangoapps/course_api/views.py
lms/djangoapps/courseware/courses.py
openedx/core/djangoapps/content/course_overviews/models.py

Backport of https://github.com/openedx/edx-platform/pull/32573
This adds the ability to get a list of detailed courses based on their keys provided in the newly added `keys` query param in the `GET /courses/v1/courses/` endpoint.
(cherry picked from commit b14cf0cc76928d3903eafcfda47dbefb44044a7a)

feat: list courses details by keys

---

cms/djangoapps/contentstore/rest_api/v1/mixins.py
cms/djangoapps/contentstore/rest_api/v1/serializers.py
cms/djangoapps/contentstore/rest_api/v1/tests/test_grading.py
cms/djangoapps/contentstore/rest_api/v1/urls.py
cms/djangoapps/contentstore/rest_api/v1/views.py
cms/djangoapps/contentstore/utils.py
cms/djangoapps/contentstore/views/course.py

(cherry picked from commit dea67f29c41e588c297973a96c522af9a25d653d)
This PR creates APIs to GET and POST course grade settings. This is a port of the upstream PR openedx/edx-platform#32399
Link to other information about the change, such as Jira issues, GitHub issues, or Discourse discussions.
Be sure to check they are publicly readable, or if not, repeat the information here.
1. Setup branch in devstack
1. Fetch Access Token:
```
curl -X POST -d "grant_type=client_credentials&client_id=studio-backend-service-key&client_secret=studio-backend-service-secret&token_type=jwt" http://localhost:18000/oauth2/access_token
```
You will get a response of the format:
```
{"access_token": "ACCESS_TOKEN", "expires_in": 36000, "token_type": "JWT", "scope": "read write email profile"}
```
1. Fetch …

feat: Create DRF for course grading (#32399)

---

lms/static/js/student_account/views/FormView.js
lms/static/js/student_account/views/LoginView.js

Backport of https://github.com/openedx/edx-platform/pull/32783, includes missing initializations in JS files that were causing JS tests to fail.
(cherry picked from commit 3025ab5fe6f6f53d6af5b36681355efafa37c74b) (cherry picked from commit 2ee57b7d59ed53fa928f9b19127038b4cf0b4620)
`Private-ref`: [BB-7694](https://tasks.opencraft.com/browse/BB-7694)
1. Set the `SHOW_REGISTRATION_LINKS` flag to `False` in both lms and cms
2. Check LMS: http://localhost:18000/ has no register button at the top
3. Check LMS: http://localhost:18000/register still works does work
4. Check LMS: http://localhost:18000/login doesn't show links to the registration form
5. Check CMS (studio): http://localhost:18010/ doesn't show links to register an account

Backport missing showRegisterLinks initializations to Nutmeg

---

lms/static/js/student_account/views/AccessView.js
lms/static/js/student_account/views/FormView.js
lms/static/js/student_account/views/LoginView.js
lms/static/js/student_account/views/RegisterView.js

Backport of https://github.com/openedx/edx-platform/pull/32783, includes missing initializations in JS files that were causing JS tests to fail.
(cherry picked from commit 3025ab5fe6f6f53d6af5b36681355efafa37c74b) (cherry picked from commit 2ee57b7d59ed53fa928f9b19127038b4cf0b4620)
`Private-ref`: [BB-7694](https://tasks.opencraft.com/browse/BB-7694)
1. Set the `SHOW_REGISTRATION_LINKS` flag to `False` in both lms and cms
2. Check LMS: http://localhost:18000/ has no register button at the top
3. Check LMS: http://localhost:18000/register still works does work
4. Check LMS: http://localhost:18000/login doesn't show links to the registration form
5. Check CMS (studio): http://localhost:18010/ doesn't show links to register an account

Backport missing showRegisterLinks initializations to Palm

---

common/djangoapps/student/roles.py
common/djangoapps/student/tests/test_roles.py
lms/djangoapps/courseware/rules.py
lms/djangoapps/instructor/access.py
lms/djangoapps/instructor/permissions.py
lms/djangoapps/instructor/tests/views/test_instructor_dashboard.py
lms/djangoapps/instructor/views/instructor_dashboard.py
lms/envs/common.py
lms/static/js/fixtures/instructor_dashboard/membership.html
lms/templates/instructor/instructor_dashboard_2/membership.html

Adds a new course team role, `eSHE Instructor`. This role inherits all `Staff` permissions, except the ability to assign course team roles and enroll / un-enroll students.
The role is designed to be composable with other roles. This means that if a user has `Staff` and `eSHE Instructor` roles, it'll have a union of permission sets of both.
Here is the default Instructor Dashboard tabs available to the new role:
The `Membership` tab is hidden here. However, if a user has both `Forum discussion` and `eSHE Instructor` role, the `Membership` tab is visible, but without the students enrollment section:
1. Switch your devstack to the `0x29a/bb7489/eshe-instructor` branch from the `git@github.com:open-craft/edx-platform.git` repo.
2. Create two users: `course_staff@example.com` and …

feat: eSHE Instructor role [BB-7489]

---

openedx/features/content_tagging/api.py
openedx/features/content_tagging/rest_api/v1/urls.py
openedx/features/content_tagging/tests/test_api.py
requirements/edx/base.txt
requirements/edx/development.txt
requirements/edx/doc.txt
requirements/edx/testing.txt

This PR exposes the retrieve object tag REST API endpoint from oel_tagging.
- Depends on https://github.com/openedx/openedx-learning/pull/68
- Run your local devstack,
- Make have https://github.com/openedx/openedx-learning/pull/68 installed locally, to do that:
- clone the branch to your DEV_STACK/src
- uninstall your existing openedx-learning package:
- `make lms-shel`
- `pip uninstall openedx-learning`
- install the branch you cloned: 
- `make lms-shell`
- `cd /edx/src`
- `pip install -e openedx-learning`
- Check that the endpoint page works:
- `http://localhost:18000/api/content_tagging/v1/object_tags/`
---
Private Ref: [FAL-3452](https://tasks.opencraft.com/browse/FAL-3452)

feat: Add retrieve object_tags REST API

---

cms/static/cms/js/require-config.js
lms/static/lms/js/require-config.js

**Backport of https://github.com/openedx/edx-platform/pull/33124**
The text plugin for requirejs is used to load text assets such as .underscore files. To avoid CORS issues when loading such assets from a different domain, such as a when a CDN is in use, this plugin loads such assets as .js files by adding a script tag.
What this means in practice is that if you configure the platform to serve static assets from a CDN, it will try to load `file.underscore.js` instead of `file.underscore`. We can override this behaviour by providing a `useXhr` function for the text plugin configuration. The plugin will use this function to determine whether to use XHR or the script tag approach.
In this change we are asking it to always use XHR since the concerns about CORS raised by the plugins …

fix: loading of underscore and other text assets over CDN

---

lms/djangoapps/instructor/permissions.py
lms/djangoapps/instructor/views/api.py

Consider [this diff](https://github.com/open-craft/edx-platform/commit/5d160c2ecd91e58276dccfd84ca32fb689f46e5e#diff-119bae82c371c32ae47e25d78423c5001a44e951e23492f31d3febe7d9c008f6R47-R53). We've modified `CAN_ENROLL` permission in a way that eSHE Instructors don't have it, but eSHE Instructor + Staff have.
However, the same permission is used to control two other endpoints that shouldn't be forbidden to eSHE Instructor. One of them, `get_student_enrollment_status`, is used for this instructor view:
So this PR fixes these two endpoints for eSHE Instructors by introducing two new permissions, specific to these endpoints, with the same access level as before.
1. Switch your devstack to the `0x29a/bb7841/fix-permissions` branch from the `git@github.com:open-craft/edx-platform.git` repo.
2. …

fix: eSHE Instructor should be able to see forum members and enrollments [BB-7841]

---

cms/djangoapps/contentstore/tests/test_course_create_rerun.py
cms/djangoapps/contentstore/views/course.py
cms/djangoapps/contentstore/views/library.py
cms/djangoapps/contentstore/views/tests/test_library.py

This PR fixes two bugs :
1. **fetch org list only for course creator granted status**:
The [get_organizations](https://github.com/open-craft/edx-platform/blob/6e79a5389e9224b452b2f698d4e71b382f3e1e65/cms/djangoapps/contentstore/views/course.py#L1832) is used to fetch a list of orgs which a user is allowed to create courses/libraries for. The course creator status for the user is used here to determine which orgs to display to the user.
However, currently all orgs are fetched for users even with course creator status in `unrequested` or `pending` state. This is a bug which is being fixed with this PR.
2. **Course instrutors cannot create new library even though course staff can**:
Currently course staff has the ability to create new libraries for their respective orgs. But when a course …

fix: fetch org list only for course creator granted status and course admin can create new library

---

requirements/edx/base.in
requirements/edx/base.txt
requirements/edx/development.txt
requirements/edx/testing.txt

This PR bumps ora2 to a version that supports the me-south-1 AWS region.
1. Try submitting a file in [the development environment](https://apps.lms.dev.eshe.edpl.us/learning/course/course-v1:ASU+CS101+2023/block-v1:ASU+CS101+2023+type@sequential+block@cbfa6ca94fc44eaf94c2a63215112dd5/block-v1:ASU+CS101+2023+type@vertical+block@083e1b735440424e91a29b897a2c3694) where this has been deployed.
2. Ensure the file is uploaded correctly.

chore: bump ora2

---

lms/djangoapps/course_wiki/middleware.py
lms/djangoapps/course_wiki/tests/test_middleware.py

Upstream PR: https://github.com/openedx/edx-platform/pull/33338
Learners want to have the usual course navigation when viewing a wiki, so that they can go back to the course related to the wiki and browse other tabs/sections of the course.
Wiki reads the course from the `request.course`. If it's not present, i.e.  None or not set on the request, it will not show the course navigation UI.
It seems like `WikiAccessMiddleware` already has the code that parses course id from the request (when the request is for a wiki view) and sets the course for the request. However, it doesn't work in most scenarios, because the course id is not in the it's normal format in most requests that go to wiki.
For example, when a leaner clicks on a wiki tab from the course overview, they are redirected to …

feat: set course for wiki based on the wiki_slug

---

requirements/edx/base.in
requirements/edx/base.txt
requirements/edx/development.txt
requirements/edx/testing.txt

The original library was removed from PyPI and GitHub.
https://discuss.openedx.org/t/missing-py2neo-package-causing-build-issues-in-all-edx-platform-releases/11371

build: replace py2neo with a fork

---

common/djangoapps/student/auth.py
common/djangoapps/student/tests/test_authz.py

Backport of https://github.com/openedx/edx-platform/pull/33491.

fix: limited staff cohorts and gradebook access [BB-7962][BACKPORT]

---

requirements/edx/base.in
requirements/edx/base.txt
requirements/edx/development.txt
requirements/edx/testing.txt

Backport of https://github.com/open-craft/edx-platform/pull/594

fix: replace py2neo with forked package

---

common/djangoapps/student/auth.py
common/djangoapps/student/tests/test_authz.py

Backport of https://github.com/openedx/edx-platform/pull/33491.

fix(nutmeg): limited staff cohorts and gradebook access [BB-7962]

---

lms/djangoapps/instructor/tests/views/test_instructor_dashboard.py
lms/djangoapps/instructor/views/instructor_dashboard.py

Backports https://github.com/openedx/edx-platform/pull/33684.
Check also masquerading role to determine if instructor tab is enabled, in order to hide it when a user with acess is masquerading as a student role without a specific different user.
Impacts Staff and Instructor users.
1. [Create a course with an enrollment track](https://edx.readthedocs.io/projects/open-edx-building-and-running-a-course/en/latest/course_features/diff_content/enroll_track_courseware.html)
2. Preview the course as a staff user
3. Use the "View this course as:" option to select one of the enrollment tracks
4. See that the "Instructor" tab is not displayed
None
Private-Ref: https://tasks.opencraft.com/browse/BB-8087

fix: check masquerade on instructor dashboard tab acess check

---

lms/djangoapps/courseware/views/views.py
lms/envs/common.py
lms/static/js/discovery/discovery_factory.js
lms/static/js/spec/discovery/discovery_factory_spec.js
lms/templates/courseware/courses.html

Adds a feature flag to filter courses by users preferred language by default
test: add test
(cherry picked from commit eca9398c098ee54a25cdb7f9612cff144c98f652)
`Private-ref`: https://tasks.opencraft.com/browse/BB-8091

feat: filter courses by user language by default
